# 导入所有模型确保 Alembic 可以检测到
from .user_models import *
from .org_models import *
from .tenant_models import *
from .tenant_backup_models import *
from .file_models import *
from .rbac_models import *
from .relationship_models import *
from .password_policy_models import *
from .oauth_models import *