"""Initial migration

Revision ID: 08848aae9e6a
Revises: 
Create Date: 2025-08-12 17:15:01.657446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08848aae9e6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_tenant_features',
    sa.Column('id', sa.Integer(), nullable=False, comment='功能定义唯一ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='功能唯一名称标识'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='功能显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='功能详细描述'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='功能分类（文件管理/用户管理等）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='功能是否激活可用'),
    sa.Column('has_quota', sa.Boolean(), nullable=False, comment='是否有使用量限制'),
    sa.Column('quota_unit', sa.String(length=20), nullable=True, comment='配额单位（count/size/api_calls等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='功能创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='功能最后更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_tenant_features_category'), 'sys_tenant_features', ['category'], unique=False)
    op.create_index(op.f('ix_sys_tenant_features_id'), 'sys_tenant_features', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_features_name'), 'sys_tenant_features', ['name'], unique=True)
    op.create_table('sys_tenants',
    sa.Column('id', sa.Integer(), nullable=False, comment='租户唯一标识ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='租户名称（组织名称）'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='租户唯一标识符，用于URL路径'),
    sa.Column('domain', sa.String(length=255), nullable=True, comment='租户自定义域名'),
    sa.Column('subdomain', sa.String(length=100), nullable=True, comment='租户子域名'),
    sa.Column('tenant_type', sa.String(length=20), nullable=False, comment='租户套餐类型'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='租户当前状态'),
    sa.Column('admin_email', sa.String(length=255), nullable=False, comment='租户管理员邮箱地址'),
    sa.Column('admin_name', sa.String(length=255), nullable=False, comment='租户管理员姓名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='租户联系电话'),
    sa.Column('address', sa.Text(), nullable=True, comment='租户联系地址'),
    sa.Column('subscription_starts_at', sa.DateTime(timezone=True), nullable=True, comment='订阅开始时间'),
    sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True, comment='订阅结束时间'),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True, comment='试用期结束时间'),
    sa.Column('max_users', sa.Integer(), nullable=False, comment='最大用户数限制'),
    sa.Column('max_storage', sa.BigInteger(), nullable=False, comment='最大存储空间限制（字节）'),
    sa.Column('max_files', sa.Integer(), nullable=False, comment='最大文件数量限制'),
    sa.Column('max_api_calls', sa.Integer(), nullable=False, comment='每月API调用次数限制'),
    sa.Column('current_users', sa.Integer(), nullable=False, comment='当前用户数量'),
    sa.Column('current_storage', sa.BigInteger(), nullable=False, comment='当前存储空间使用量（字节）'),
    sa.Column('current_files', sa.Integer(), nullable=False, comment='当前文件数量'),
    sa.Column('current_api_calls', sa.Integer(), nullable=False, comment='当月API调用次数'),
    sa.Column('features', sa.JSON(), nullable=True, comment='租户可用功能列表（JSON格式）'),
    sa.Column('settings', sa.JSON(), nullable=True, comment='租户自定义设置（JSON格式）'),
    sa.Column('database_name', sa.String(length=100), nullable=True, comment='租户专用数据库名称'),
    sa.Column('database_config', sa.JSON(), nullable=True, comment='数据库连接配置（JSON格式）'),
    sa.Column('integrations', sa.JSON(), nullable=True, comment='第三方系统集成配置（JSON格式）'),
    sa.Column('allowed_ips', sa.JSON(), nullable=True, comment='IP地址白名单（JSON数组格式）'),
    sa.Column('require_2fa', sa.Boolean(), nullable=False, comment='是否强制要求双因素认证'),
    sa.Column('password_policy', sa.JSON(), nullable=True, comment='密码策略配置（JSON格式）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='租户创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='租户最后更新时间'),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True, comment='租户最后活动时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_tenants_admin_email'), 'sys_tenants', ['admin_email'], unique=False)
    op.create_index(op.f('ix_sys_tenants_created_at'), 'sys_tenants', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_tenants_domain'), 'sys_tenants', ['domain'], unique=True)
    op.create_index(op.f('ix_sys_tenants_id'), 'sys_tenants', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenants_name'), 'sys_tenants', ['name'], unique=False)
    op.create_index(op.f('ix_sys_tenants_slug'), 'sys_tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_sys_tenants_status'), 'sys_tenants', ['status'], unique=False)
    op.create_index(op.f('ix_sys_tenants_subdomain'), 'sys_tenants', ['subdomain'], unique=True)
    op.create_table('sys_organizations',
    sa.Column('id', sa.Integer(), nullable=False, comment='组织机构唯一标识ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='所属租户ID，用于多租户数据隔离'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='组织名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='组织编码，同租户内唯一'),
    sa.Column('description', sa.Text(), nullable=True, comment='组织描述信息'),
    sa.Column('logo_url', sa.String(length=500), nullable=True, comment='组织Logo图片URL'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='组织地址'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='联系邮箱'),
    sa.Column('website', sa.String(length=200), nullable=True, comment='官方网站'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父组织ID（null表示顶级组织）'),
    sa.Column('path', sa.String(length=1000), nullable=False, comment='组织完整路径（/org1/org2/org3）'),
    sa.Column('level', sa.Integer(), nullable=False, comment='组织层级深度（0为顶级）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='同级组织排序顺序'),
    sa.Column('third_party_provider', sa.String(length=50), nullable=True, comment='第三方系统提供商（LDAP/AD等）'),
    sa.Column('third_party_id', sa.String(length=255), nullable=True, comment='第三方系统中的组织ID'),
    sa.Column('third_party_data', sa.JSON(), nullable=True, comment='第三方系统返回的扩展数据（JSON格式）'),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False, comment='是否启用与第三方系统同步'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='最后同步时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='组织是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='组织创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='组织最后更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='执行删除操作的用户ID'),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_organizations_code'), 'sys_organizations', ['code'], unique=False)
    op.create_index(op.f('ix_sys_organizations_id'), 'sys_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_sys_organizations_is_deleted'), 'sys_organizations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_organizations_name'), 'sys_organizations', ['name'], unique=False)
    op.create_index(op.f('ix_sys_organizations_parent_id'), 'sys_organizations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_organizations_path'), 'sys_organizations', ['path'], unique=False)
    op.create_index(op.f('ix_sys_organizations_tenant_id'), 'sys_organizations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_organizations_third_party_id'), 'sys_organizations', ['third_party_id'], unique=False)
    op.create_table('sys_tenant_feature_access',
    sa.Column('id', sa.Integer(), nullable=False, comment='功能访问权限记录ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='租户ID'),
    sa.Column('feature_id', sa.Integer(), nullable=False, comment='功能定义ID'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='功能是否对该租户开放'),
    sa.Column('quota_limit', sa.BigInteger(), nullable=True, comment='配额上限（null表示无限制）'),
    sa.Column('quota_used', sa.BigInteger(), nullable=False, comment='已使用的配额数量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='权限配置创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='权限配置最后更新时间'),
    sa.ForeignKeyConstraint(['feature_id'], ['sys_tenant_features.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='租户功能访问权限表，管理租户对各功能的访问权限'
    )
    op.create_index(op.f('ix_sys_tenant_feature_access_feature_id'), 'sys_tenant_feature_access', ['feature_id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_feature_access_id'), 'sys_tenant_feature_access', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_feature_access_tenant_id'), 'sys_tenant_feature_access', ['tenant_id'], unique=False)
    op.create_table('sys_tenant_usage_metrics',
    sa.Column('id', sa.Integer(), nullable=False, comment='使用量指标记录ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='所属租户ID'),
    sa.Column('metric_name', sa.String(length=100), nullable=False, comment='指标名称（api_calls/storage_used等）'),
    sa.Column('metric_value', sa.BigInteger(), nullable=False, comment='指标数值'),
    sa.Column('metric_unit', sa.String(length=20), nullable=True, comment='数值单位（bytes/count/seconds等）'),
    sa.Column('year', sa.Integer(), nullable=False, comment='统计年份'),
    sa.Column('month', sa.Integer(), nullable=False, comment='统计月份（1-12）'),
    sa.Column('day', sa.Integer(), nullable=False, comment='统计日期（1-31）'),
    sa.Column('hour', sa.Integer(), nullable=True, comment='统计小时（0-23，可为空）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='指标记录创建时间'),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_tenant_usage_metrics_created_at'), 'sys_tenant_usage_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_tenant_usage_metrics_day'), 'sys_tenant_usage_metrics', ['day'], unique=False)
    op.create_index(op.f('ix_sys_tenant_usage_metrics_hour'), 'sys_tenant_usage_metrics', ['hour'], unique=False)
    op.create_index(op.f('ix_sys_tenant_usage_metrics_id'), 'sys_tenant_usage_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_usage_metrics_metric_name'), 'sys_tenant_usage_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_sys_tenant_usage_metrics_month'), 'sys_tenant_usage_metrics', ['month'], unique=False)
    op.create_index(op.f('ix_sys_tenant_usage_metrics_tenant_id'), 'sys_tenant_usage_metrics', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_usage_metrics_year'), 'sys_tenant_usage_metrics', ['year'], unique=False)
    op.create_table('sys_departments',
    sa.Column('id', sa.Integer(), nullable=False, comment='部门唯一标识ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='部门名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='部门编码，组织内唯一'),
    sa.Column('description', sa.Text(), nullable=True, comment='部门描述信息'),
    sa.Column('org_id', sa.Integer(), nullable=False, comment='所属组织ID'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父部门ID（null表示顶级部门）'),
    sa.Column('path', sa.String(length=1000), nullable=False, comment='部门完整路径（/dept1/dept2/dept3）'),
    sa.Column('level', sa.Integer(), nullable=False, comment='部门层级深度（0为顶级）'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='同级部门排序顺序'),
    sa.Column('manager_id', sa.Integer(), nullable=True, comment='部门经理/负责人用户ID'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='部门联系电话'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='部门联系邮箱'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='部门办公地址'),
    sa.Column('third_party_provider', sa.String(length=50), nullable=True, comment='第三方系统提供商（HR系统等）'),
    sa.Column('third_party_id', sa.String(length=255), nullable=True, comment='第三方系统中的部门ID'),
    sa.Column('third_party_data', sa.JSON(), nullable=True, comment='第三方系统返回的扩展数据（JSON格式）'),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False, comment='是否启用与第三方系统同步'),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True, comment='最后同步时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='部门是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='部门创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='部门最后更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='执行删除操作的用户ID'),
    sa.ForeignKeyConstraint(['org_id'], ['sys_organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_departments_code'), 'sys_departments', ['code'], unique=False)
    op.create_index(op.f('ix_sys_departments_id'), 'sys_departments', ['id'], unique=False)
    op.create_index(op.f('ix_sys_departments_is_deleted'), 'sys_departments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_departments_manager_id'), 'sys_departments', ['manager_id'], unique=False)
    op.create_index(op.f('ix_sys_departments_name'), 'sys_departments', ['name'], unique=False)
    op.create_index(op.f('ix_sys_departments_org_id'), 'sys_departments', ['org_id'], unique=False)
    op.create_index(op.f('ix_sys_departments_parent_id'), 'sys_departments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_departments_path'), 'sys_departments', ['path'], unique=False)
    op.create_index(op.f('ix_sys_departments_third_party_id'), 'sys_departments', ['third_party_id'], unique=False)
    op.create_table('sys_users',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户唯一标识ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='所属租户ID，用于多租户数据隔离'),
    sa.Column('email', sa.String(), nullable=False, comment='用户邮箱地址，多租户下可重复'),
    sa.Column('username', sa.String(), nullable=False, comment='用户名，多租户下可重复'),
    sa.Column('full_name', sa.String(), nullable=True, comment='用户真实姓名'),
    sa.Column('hashed_password', sa.String(), nullable=True, comment='加密后的密码hash，第三方认证用户可为空'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='账户是否激活，控制登录权限'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='是否为超级管理员'),
    sa.Column('is_verified', sa.Boolean(), nullable=True, comment='邮箱是否已验证'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='用户当前状态（激活/停用/暂停/删除等）'),
    sa.Column('avatar_url', sa.String(), nullable=True, comment='用户头像URL'),
    sa.Column('phone', sa.String(), nullable=True, comment='联系电话'),
    sa.Column('third_party_provider', sa.String(length=50), nullable=False, comment='认证提供商类型（本地/LDAP/SAML/OAuth2等）'),
    sa.Column('third_party_id', sa.String(length=255), nullable=True, comment='第三方系统中的用户唯一标识ID'),
    sa.Column('third_party_data', sa.JSON(), nullable=True, comment='第三方系统返回的用户扩展数据（JSON格式）'),
    sa.Column('org_id', sa.Integer(), nullable=True, comment='所属组织ID'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='所属部门ID'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='职位名称'),
    sa.Column('employee_id', sa.String(length=50), nullable=True, comment='员工工号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='账户创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='最后更新时间'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已软删除（回收站功能）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='执行删除操作的用户ID'),
    sa.ForeignKeyConstraint(['deleted_by'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['sys_departments.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['sys_organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户主表，存储系统中所有用户的基本信息和状态'
    )
    op.create_index(op.f('ix_sys_users_department_id'), 'sys_users', ['department_id'], unique=False)
    op.create_index(op.f('ix_sys_users_email'), 'sys_users', ['email'], unique=False)
    op.create_index(op.f('ix_sys_users_employee_id'), 'sys_users', ['employee_id'], unique=False)
    op.create_index(op.f('ix_sys_users_id'), 'sys_users', ['id'], unique=False)
    op.create_index(op.f('ix_sys_users_is_deleted'), 'sys_users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_users_org_id'), 'sys_users', ['org_id'], unique=False)
    op.create_index(op.f('ix_sys_users_status'), 'sys_users', ['status'], unique=False)
    op.create_index(op.f('ix_sys_users_tenant_id'), 'sys_users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_users_third_party_id'), 'sys_users', ['third_party_id'], unique=False)
    op.create_index(op.f('ix_sys_users_username'), 'sys_users', ['username'], unique=False)
    op.create_table('sys_file_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_file_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_owner_name', 'sys_file_categories', ['owner_id', 'name'], unique=False)
    op.create_index('idx_category_path', 'sys_file_categories', ['path'], unique=False)
    op.create_index(op.f('ix_sys_file_categories_id'), 'sys_file_categories', ['id'], unique=False)
    op.create_index(op.f('ix_sys_file_categories_name'), 'sys_file_categories', ['name'], unique=False)
    op.create_index(op.f('ix_sys_file_categories_owner_id'), 'sys_file_categories', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sys_file_categories_parent_id'), 'sys_file_categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_file_categories_path'), 'sys_file_categories', ['path'], unique=False)
    op.create_table('sys_file_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tag_owner_name', 'sys_file_tags', ['owner_id', 'name'], unique=False)
    op.create_index('idx_tag_usage', 'sys_file_tags', ['usage_count'], unique=False)
    op.create_index(op.f('ix_sys_file_tags_id'), 'sys_file_tags', ['id'], unique=False)
    op.create_index(op.f('ix_sys_file_tags_name'), 'sys_file_tags', ['name'], unique=False)
    op.create_index(op.f('ix_sys_file_tags_owner_id'), 'sys_file_tags', ['owner_id'], unique=False)
    op.create_table('sys_folders',
    sa.Column('id', sa.Integer(), nullable=False, comment='文件夹唯一标识ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='文件夹名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='文件夹描述信息'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父文件夹ID（null表示根目录）'),
    sa.Column('path', sa.String(length=1000), nullable=False, comment='文件夹完整路径（/root/folder1/folder2）'),
    sa.Column('level', sa.Integer(), nullable=False, comment='文件夹层级深度（0为根目录）'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='文件夹所有者用户ID'),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='文件夹可见性级别'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统预定义文件夹（不可删除）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='文件夹创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='文件夹最后更新时间'),
    sa.ForeignKeyConstraint(['owner_id'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='文件夹表，管理文件的层级组织结构'
    )
    op.create_index('idx_folder_owner_parent', 'sys_folders', ['owner_id', 'parent_id'], unique=False)
    op.create_index('idx_folder_path', 'sys_folders', ['path'], unique=False)
    op.create_index(op.f('ix_sys_folders_id'), 'sys_folders', ['id'], unique=False)
    op.create_index(op.f('ix_sys_folders_name'), 'sys_folders', ['name'], unique=False)
    op.create_index(op.f('ix_sys_folders_owner_id'), 'sys_folders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sys_folders_parent_id'), 'sys_folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_folders_path'), 'sys_folders', ['path'], unique=False)
    op.create_table('sys_permissions',
    sa.Column('id', sa.Integer(), nullable=False, comment='权限ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='权限名称，全局唯一，格式：resource:action'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='权限显示名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='权限描述'),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='资源类型（user/file/organization/department等）'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型（create/read/update/delete/manage等）'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='权限分类（用户管理/文件管理等）'),
    sa.Column('group_name', sa.String(length=100), nullable=True, comment='权限分组名称'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父权限ID，支持权限层级'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统权限（不可删除）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='权限是否激活'),
    sa.Column('require_owner', sa.Boolean(), nullable=False, comment='是否需要资源所有者权限（如只能删除自己的文件）'),
    sa.Column('conditions', sa.JSON(), nullable=True, comment='权限执行条件（JSON格式），支持复杂的动态权限控制'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='权限创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='最后更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='执行删除的用户ID'),
    sa.ForeignKeyConstraint(['deleted_by'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_permissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='权限表，定义系统中的所有权限点和权限层级'
    )
    op.create_index(op.f('ix_sys_permissions_action'), 'sys_permissions', ['action'], unique=False)
    op.create_index(op.f('ix_sys_permissions_category'), 'sys_permissions', ['category'], unique=False)
    op.create_index(op.f('ix_sys_permissions_group_name'), 'sys_permissions', ['group_name'], unique=False)
    op.create_index(op.f('ix_sys_permissions_id'), 'sys_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_sys_permissions_is_deleted'), 'sys_permissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_permissions_name'), 'sys_permissions', ['name'], unique=True)
    op.create_index(op.f('ix_sys_permissions_resource_type'), 'sys_permissions', ['resource_type'], unique=False)
    op.create_table('sys_roles',
    sa.Column('id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='所属租户ID，用于多租户角色隔离'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='角色名称，租户内唯一'),
    sa.Column('display_name', sa.String(length=255), nullable=False, comment='角色显示名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='角色描述'),
    sa.Column('role_type', sa.String(length=20), nullable=False, comment='角色类型（system=系统角色, tenant=租户角色, custom=自定义角色）'),
    sa.Column('level', sa.Integer(), nullable=False, comment='角色级别，数字越大权限越高，用于权限继承和冲突解决'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='角色是否激活'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统预定义角色（不可删除）'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为新用户默认角色'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父角色ID，支持角色继承'),
    sa.Column('max_users', sa.Integer(), nullable=True, comment='该角色最大用户数限制（null表示无限制）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='角色创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='最后更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者用户ID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='是否已软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.Integer(), nullable=True, comment='执行删除的用户ID'),
    sa.ForeignKeyConstraint(['created_by'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_roles.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_role_tenant_name'),
    comment='角色表，定义系统中的各种角色及其层级关系'
    )
    op.create_index(op.f('ix_sys_roles_id'), 'sys_roles', ['id'], unique=False)
    op.create_index(op.f('ix_sys_roles_is_deleted'), 'sys_roles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sys_roles_name'), 'sys_roles', ['name'], unique=False)
    op.create_index(op.f('ix_sys_roles_tenant_id'), 'sys_roles', ['tenant_id'], unique=False)
    op.create_table('sys_tenant_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='审计日志记录ID'),
    sa.Column('tenant_id', sa.Integer(), nullable=False, comment='所属租户ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户ID（系统操作时可为空）'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='操作类型（create/update/delete/login等）'),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='操作的资源类型（user/file/organization等）'),
    sa.Column('resource_id', sa.String(length=100), nullable=True, comment='具体资源的ID标识'),
    sa.Column('old_values', sa.JSON(), nullable=True, comment='修改前的数据值（JSON格式）'),
    sa.Column('new_values', sa.JSON(), nullable=True, comment='修改后的数据值（JSON格式）'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='操作者IP地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理信息（浏览器等）'),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='请求追踪ID，用于分布式链路追踪'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='审计记录创建时间'),
    sa.ForeignKeyConstraint(['tenant_id'], ['sys_tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_tenant_audit_logs_action'), 'sys_tenant_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_sys_tenant_audit_logs_created_at'), 'sys_tenant_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_tenant_audit_logs_id'), 'sys_tenant_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_audit_logs_request_id'), 'sys_tenant_audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_audit_logs_tenant_id'), 'sys_tenant_audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_audit_logs_user_id'), 'sys_tenant_audit_logs', ['user_id'], unique=False)
    op.create_table('sys_user_sessions',
    sa.Column('id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='会话所属用户ID'),
    sa.Column('refresh_token', sa.String(), nullable=False, comment='JWT刷新令牌，全局唯一'),
    sa.Column('device_info', sa.String(), nullable=True, comment='设备信息（浏览器User-Agent等）'),
    sa.Column('ip_address', sa.String(), nullable=True, comment='登录IP地址'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='会话是否活跃'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='会话过期时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='会话创建时间'),
    sa.Column('last_used', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='最后使用时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户会话表，管理用户登录会话和刷新令牌'
    )
    op.create_index(op.f('ix_sys_user_sessions_id'), 'sys_user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_sessions_refresh_token'), 'sys_user_sessions', ['refresh_token'], unique=True)
    op.create_table('sys_user_verifications',
    sa.Column('id', sa.Integer(), nullable=False, comment='验证记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='验证码所属用户ID'),
    sa.Column('verification_type', sa.String(), nullable=False, comment='验证类型（email/phone/password_reset/two_factor）'),
    sa.Column('verification_code', sa.String(), nullable=False, comment='验证码内容'),
    sa.Column('is_used', sa.Boolean(), nullable=True, comment='验证码是否已使用'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='验证码过期时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='验证码生成时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户验证码表，存储各类验证码信息（邮箱验证、手机验证、密码重置等）'
    )
    op.create_index(op.f('ix_sys_user_verifications_id'), 'sys_user_verifications', ['id'], unique=False)
    op.create_table('sys_files',
    sa.Column('id', sa.Integer(), nullable=False, comment='文件唯一标识ID'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='用户上传时的原始文件名'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='系统生成的存储文件名（UUID）'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件在MinIO对象存储中的完整路径'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小（字节）'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='文件类型分类（document/image/video等）'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='文件MIME类型（application/pdf等）'),
    sa.Column('file_extension', sa.String(length=20), nullable=True, comment='文件扩展名（不含点号）'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='文件标题（用户自定义）'),
    sa.Column('description', sa.Text(), nullable=True, comment='文件描述信息'),
    sa.Column('tags', sa.Text(), nullable=True, comment='文件标签列表（JSON格式存储）'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='文件自定义分类'),
    sa.Column('keywords', sa.Text(), nullable=True, comment='文件搜索关键词（用于全文搜索）'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='文件SHA256哈希值，用于完整性校验和去重'),
    sa.Column('version', sa.Integer(), nullable=False, comment='文件版本号，从1开始递增'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='文件当前状态（active/deleted/archived等）'),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='文件可见性级别（private/internal/shared/public）'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='文件所有者用户ID'),
    sa.Column('parent_folder_id', sa.Integer(), nullable=True, comment='父文件夹ID（null表示根目录）'),
    sa.Column('download_count', sa.Integer(), nullable=False, comment='文件下载次数统计'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='文件查看次数统计'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='文件创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='文件最后更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='文件删除时间（软删除）'),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True, comment='文件最后访问时间'),
    sa.ForeignKeyConstraint(['owner_id'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['sys_folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name'),
    comment='文件主表，存储所有文件的基本信息和元数据'
    )
    op.create_index('idx_file_category', 'sys_files', ['category'], unique=False)
    op.create_index('idx_file_created', 'sys_files', ['created_at'], unique=False)
    op.create_index('idx_file_hash', 'sys_files', ['file_hash'], unique=False)
    op.create_index('idx_file_owner_category', 'sys_files', ['owner_id', 'category'], unique=False)
    op.create_index('idx_file_owner_status', 'sys_files', ['owner_id', 'status'], unique=False)
    op.create_index('idx_file_type_status', 'sys_files', ['file_type', 'status'], unique=False)
    op.create_index(op.f('ix_sys_files_category'), 'sys_files', ['category'], unique=False)
    op.create_index(op.f('ix_sys_files_created_at'), 'sys_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_files_file_extension'), 'sys_files', ['file_extension'], unique=False)
    op.create_index(op.f('ix_sys_files_file_hash'), 'sys_files', ['file_hash'], unique=False)
    op.create_index(op.f('ix_sys_files_file_type'), 'sys_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_sys_files_id'), 'sys_files', ['id'], unique=False)
    op.create_index(op.f('ix_sys_files_original_name'), 'sys_files', ['original_name'], unique=False)
    op.create_index(op.f('ix_sys_files_owner_id'), 'sys_files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sys_files_parent_folder_id'), 'sys_files', ['parent_folder_id'], unique=False)
    op.create_index(op.f('ix_sys_files_status'), 'sys_files', ['status'], unique=False)
    op.create_index(op.f('ix_sys_files_title'), 'sys_files', ['title'], unique=False)
    op.create_index(op.f('ix_sys_files_visibility'), 'sys_files', ['visibility'], unique=False)
    op.create_table('sys_role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sys_user_permissions',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户权限记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='权限ID'),
    sa.Column('granted', sa.Boolean(), nullable=False, comment='权限授予状态（True=授予权限, False=明确拒绝权限）'),
    sa.Column('resource_id', sa.String(length=100), nullable=True, comment='特定资源ID，为空表示全局权限'),
    sa.Column('conditions', sa.JSON(), nullable=True, comment='权限执行的额外条件（JSON格式）'),
    sa.Column('granted_by', sa.Integer(), nullable=True, comment='授权者用户ID'),
    sa.Column('reason', sa.String(length=500), nullable=True, comment='授权原因说明'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='权限过期时间（null表示永不过期）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='权限是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='权限分配时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='最后更新时间'),
    sa.ForeignKeyConstraint(['granted_by'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', 'resource_id', name='uq_user_permission_resource'),
    comment='用户直接权限表，存储用户级别的精细化权限控制'
    )
    op.create_index(op.f('ix_sys_user_permissions_id'), 'sys_user_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_permissions_permission_id'), 'sys_user_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_sys_user_permissions_user_id'), 'sys_user_permissions', ['user_id'], unique=False)
    op.create_table('sys_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['sys_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('sys_file_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['sys_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_file_action', 'sys_file_activities', ['file_id', 'action'], unique=False)
    op.create_index('idx_activity_user_time', 'sys_file_activities', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sys_file_activities_action'), 'sys_file_activities', ['action'], unique=False)
    op.create_index(op.f('ix_sys_file_activities_created_at'), 'sys_file_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_file_activities_file_id'), 'sys_file_activities', ['file_id'], unique=False)
    op.create_index(op.f('ix_sys_file_activities_id'), 'sys_file_activities', ['id'], unique=False)
    op.create_table('sys_file_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['sys_files.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_file_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_file_comments_file_id'), 'sys_file_comments', ['file_id'], unique=False)
    op.create_index(op.f('ix_sys_file_comments_id'), 'sys_file_comments', ['id'], unique=False)
    op.create_table('sys_file_shares',
    sa.Column('id', sa.Integer(), nullable=False, comment='文件分享记录ID'),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('shared_by', sa.Integer(), nullable=False),
    sa.Column('shared_with', sa.Integer(), nullable=True),
    sa.Column('access_type', sa.String(length=20), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('password_protected', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['sys_files.id'], ),
    sa.ForeignKeyConstraint(['shared_by'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['shared_with'], ['sys_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index(op.f('ix_sys_file_shares_file_id'), 'sys_file_shares', ['file_id'], unique=False)
    op.create_index(op.f('ix_sys_file_shares_id'), 'sys_file_shares', ['id'], unique=False)
    op.create_table('sys_file_tag_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['sys_files.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['sys_file_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_file_tag_unique', 'sys_file_tag_relations', ['file_id', 'tag_id'], unique=True)
    op.create_index(op.f('ix_sys_file_tag_relations_file_id'), 'sys_file_tag_relations', ['file_id'], unique=False)
    op.create_index(op.f('ix_sys_file_tag_relations_id'), 'sys_file_tag_relations', ['id'], unique=False)
    op.create_index(op.f('ix_sys_file_tag_relations_tag_id'), 'sys_file_tag_relations', ['tag_id'], unique=False)
    op.create_table('sys_file_versions',
    sa.Column('id', sa.Integer(), nullable=False, comment='文件版本记录ID'),
    sa.Column('file_id', sa.Integer(), nullable=False, comment='关联的文件ID'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='版本号（从1开始递增）'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='版本文件存储名称'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='版本文件在MinIO中的存储路径'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='版本文件大小（字节）'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='版本文件SHA256哈希值'),
    sa.Column('change_description', sa.Text(), nullable=True, comment='版本变更描述'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='版本创建者用户ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='版本创建时间'),
    sa.ForeignKeyConstraint(['created_by'], ['sys_users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['sys_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_file_versions_file_id'), 'sys_file_versions', ['file_id'], unique=False)
    op.create_index(op.f('ix_sys_file_versions_id'), 'sys_file_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_file_versions_id'), table_name='sys_file_versions')
    op.drop_index(op.f('ix_sys_file_versions_file_id'), table_name='sys_file_versions')
    op.drop_table('sys_file_versions')
    op.drop_index(op.f('ix_sys_file_tag_relations_tag_id'), table_name='sys_file_tag_relations')
    op.drop_index(op.f('ix_sys_file_tag_relations_id'), table_name='sys_file_tag_relations')
    op.drop_index(op.f('ix_sys_file_tag_relations_file_id'), table_name='sys_file_tag_relations')
    op.drop_index('idx_file_tag_unique', table_name='sys_file_tag_relations')
    op.drop_table('sys_file_tag_relations')
    op.drop_index(op.f('ix_sys_file_shares_id'), table_name='sys_file_shares')
    op.drop_index(op.f('ix_sys_file_shares_file_id'), table_name='sys_file_shares')
    op.drop_table('sys_file_shares')
    op.drop_index(op.f('ix_sys_file_comments_id'), table_name='sys_file_comments')
    op.drop_index(op.f('ix_sys_file_comments_file_id'), table_name='sys_file_comments')
    op.drop_table('sys_file_comments')
    op.drop_index(op.f('ix_sys_file_activities_id'), table_name='sys_file_activities')
    op.drop_index(op.f('ix_sys_file_activities_file_id'), table_name='sys_file_activities')
    op.drop_index(op.f('ix_sys_file_activities_created_at'), table_name='sys_file_activities')
    op.drop_index(op.f('ix_sys_file_activities_action'), table_name='sys_file_activities')
    op.drop_index('idx_activity_user_time', table_name='sys_file_activities')
    op.drop_index('idx_activity_file_action', table_name='sys_file_activities')
    op.drop_table('sys_file_activities')
    op.drop_table('sys_user_roles')
    op.drop_index(op.f('ix_sys_user_permissions_user_id'), table_name='sys_user_permissions')
    op.drop_index(op.f('ix_sys_user_permissions_permission_id'), table_name='sys_user_permissions')
    op.drop_index(op.f('ix_sys_user_permissions_id'), table_name='sys_user_permissions')
    op.drop_table('sys_user_permissions')
    op.drop_table('sys_role_permissions')
    op.drop_index(op.f('ix_sys_files_visibility'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_title'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_status'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_parent_folder_id'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_owner_id'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_original_name'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_id'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_file_type'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_file_hash'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_file_extension'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_created_at'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_category'), table_name='sys_files')
    op.drop_index('idx_file_type_status', table_name='sys_files')
    op.drop_index('idx_file_owner_status', table_name='sys_files')
    op.drop_index('idx_file_owner_category', table_name='sys_files')
    op.drop_index('idx_file_hash', table_name='sys_files')
    op.drop_index('idx_file_created', table_name='sys_files')
    op.drop_index('idx_file_category', table_name='sys_files')
    op.drop_table('sys_files')
    op.drop_index(op.f('ix_sys_user_verifications_id'), table_name='sys_user_verifications')
    op.drop_table('sys_user_verifications')
    op.drop_index(op.f('ix_sys_user_sessions_refresh_token'), table_name='sys_user_sessions')
    op.drop_index(op.f('ix_sys_user_sessions_id'), table_name='sys_user_sessions')
    op.drop_table('sys_user_sessions')
    op.drop_index(op.f('ix_sys_tenant_audit_logs_user_id'), table_name='sys_tenant_audit_logs')
    op.drop_index(op.f('ix_sys_tenant_audit_logs_tenant_id'), table_name='sys_tenant_audit_logs')
    op.drop_index(op.f('ix_sys_tenant_audit_logs_request_id'), table_name='sys_tenant_audit_logs')
    op.drop_index(op.f('ix_sys_tenant_audit_logs_id'), table_name='sys_tenant_audit_logs')
    op.drop_index(op.f('ix_sys_tenant_audit_logs_created_at'), table_name='sys_tenant_audit_logs')
    op.drop_index(op.f('ix_sys_tenant_audit_logs_action'), table_name='sys_tenant_audit_logs')
    op.drop_table('sys_tenant_audit_logs')
    op.drop_index(op.f('ix_sys_roles_tenant_id'), table_name='sys_roles')
    op.drop_index(op.f('ix_sys_roles_name'), table_name='sys_roles')
    op.drop_index(op.f('ix_sys_roles_is_deleted'), table_name='sys_roles')
    op.drop_index(op.f('ix_sys_roles_id'), table_name='sys_roles')
    op.drop_table('sys_roles')
    op.drop_index(op.f('ix_sys_permissions_resource_type'), table_name='sys_permissions')
    op.drop_index(op.f('ix_sys_permissions_name'), table_name='sys_permissions')
    op.drop_index(op.f('ix_sys_permissions_is_deleted'), table_name='sys_permissions')
    op.drop_index(op.f('ix_sys_permissions_id'), table_name='sys_permissions')
    op.drop_index(op.f('ix_sys_permissions_group_name'), table_name='sys_permissions')
    op.drop_index(op.f('ix_sys_permissions_category'), table_name='sys_permissions')
    op.drop_index(op.f('ix_sys_permissions_action'), table_name='sys_permissions')
    op.drop_table('sys_permissions')
    op.drop_index(op.f('ix_sys_folders_path'), table_name='sys_folders')
    op.drop_index(op.f('ix_sys_folders_parent_id'), table_name='sys_folders')
    op.drop_index(op.f('ix_sys_folders_owner_id'), table_name='sys_folders')
    op.drop_index(op.f('ix_sys_folders_name'), table_name='sys_folders')
    op.drop_index(op.f('ix_sys_folders_id'), table_name='sys_folders')
    op.drop_index('idx_folder_path', table_name='sys_folders')
    op.drop_index('idx_folder_owner_parent', table_name='sys_folders')
    op.drop_table('sys_folders')
    op.drop_index(op.f('ix_sys_file_tags_owner_id'), table_name='sys_file_tags')
    op.drop_index(op.f('ix_sys_file_tags_name'), table_name='sys_file_tags')
    op.drop_index(op.f('ix_sys_file_tags_id'), table_name='sys_file_tags')
    op.drop_index('idx_tag_usage', table_name='sys_file_tags')
    op.drop_index('idx_tag_owner_name', table_name='sys_file_tags')
    op.drop_table('sys_file_tags')
    op.drop_index(op.f('ix_sys_file_categories_path'), table_name='sys_file_categories')
    op.drop_index(op.f('ix_sys_file_categories_parent_id'), table_name='sys_file_categories')
    op.drop_index(op.f('ix_sys_file_categories_owner_id'), table_name='sys_file_categories')
    op.drop_index(op.f('ix_sys_file_categories_name'), table_name='sys_file_categories')
    op.drop_index(op.f('ix_sys_file_categories_id'), table_name='sys_file_categories')
    op.drop_index('idx_category_path', table_name='sys_file_categories')
    op.drop_index('idx_category_owner_name', table_name='sys_file_categories')
    op.drop_table('sys_file_categories')
    op.drop_index(op.f('ix_sys_users_username'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_third_party_id'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_tenant_id'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_status'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_org_id'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_is_deleted'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_id'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_employee_id'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_email'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_department_id'), table_name='sys_users')
    op.drop_table('sys_users')
    op.drop_index(op.f('ix_sys_departments_third_party_id'), table_name='sys_departments')
    op.drop_index(op.f('ix_sys_departments_path'), table_name='sys_departments')
    op.drop_index(op.f('ix_sys_departments_parent_id'), table_name='sys_departments')
    op.drop_index(op.f('ix_sys_departments_org_id'), table_name='sys_departments')
    op.drop_index(op.f('ix_sys_departments_name'), table_name='sys_departments')
    op.drop_index(op.f('ix_sys_departments_manager_id'), table_name='sys_departments')
    op.drop_index(op.f('ix_sys_departments_is_deleted'), table_name='sys_departments')
    op.drop_index(op.f('ix_sys_departments_id'), table_name='sys_departments')
    op.drop_index(op.f('ix_sys_departments_code'), table_name='sys_departments')
    op.drop_table('sys_departments')
    op.drop_index(op.f('ix_sys_tenant_usage_metrics_year'), table_name='sys_tenant_usage_metrics')
    op.drop_index(op.f('ix_sys_tenant_usage_metrics_tenant_id'), table_name='sys_tenant_usage_metrics')
    op.drop_index(op.f('ix_sys_tenant_usage_metrics_month'), table_name='sys_tenant_usage_metrics')
    op.drop_index(op.f('ix_sys_tenant_usage_metrics_metric_name'), table_name='sys_tenant_usage_metrics')
    op.drop_index(op.f('ix_sys_tenant_usage_metrics_id'), table_name='sys_tenant_usage_metrics')
    op.drop_index(op.f('ix_sys_tenant_usage_metrics_hour'), table_name='sys_tenant_usage_metrics')
    op.drop_index(op.f('ix_sys_tenant_usage_metrics_day'), table_name='sys_tenant_usage_metrics')
    op.drop_index(op.f('ix_sys_tenant_usage_metrics_created_at'), table_name='sys_tenant_usage_metrics')
    op.drop_table('sys_tenant_usage_metrics')
    op.drop_index(op.f('ix_sys_tenant_feature_access_tenant_id'), table_name='sys_tenant_feature_access')
    op.drop_index(op.f('ix_sys_tenant_feature_access_id'), table_name='sys_tenant_feature_access')
    op.drop_index(op.f('ix_sys_tenant_feature_access_feature_id'), table_name='sys_tenant_feature_access')
    op.drop_table('sys_tenant_feature_access')
    op.drop_index(op.f('ix_sys_organizations_third_party_id'), table_name='sys_organizations')
    op.drop_index(op.f('ix_sys_organizations_tenant_id'), table_name='sys_organizations')
    op.drop_index(op.f('ix_sys_organizations_path'), table_name='sys_organizations')
    op.drop_index(op.f('ix_sys_organizations_parent_id'), table_name='sys_organizations')
    op.drop_index(op.f('ix_sys_organizations_name'), table_name='sys_organizations')
    op.drop_index(op.f('ix_sys_organizations_is_deleted'), table_name='sys_organizations')
    op.drop_index(op.f('ix_sys_organizations_id'), table_name='sys_organizations')
    op.drop_index(op.f('ix_sys_organizations_code'), table_name='sys_organizations')
    op.drop_table('sys_organizations')
    op.drop_index(op.f('ix_sys_tenants_subdomain'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_status'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_slug'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_name'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_id'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_domain'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_created_at'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_admin_email'), table_name='sys_tenants')
    op.drop_table('sys_tenants')
    op.drop_index(op.f('ix_sys_tenant_features_name'), table_name='sys_tenant_features')
    op.drop_index(op.f('ix_sys_tenant_features_id'), table_name='sys_tenant_features')
    op.drop_index(op.f('ix_sys_tenant_features_category'), table_name='sys_tenant_features')
    op.drop_table('sys_tenant_features')
    # ### end Alembic commands ###
