"""add soft delete fields to organizations

Revision ID: 147df3af577f
Revises: 91707568750f
Create Date: 2025-08-17 12:12:12.300926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147df3af577f'
down_revision: Union[str, None] = '91707568750f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_organizations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'))
    op.add_column('sys_organizations', sa.Column('deleted_by', sa.String(length=50), nullable=True, comment='删除者ID'))
    op.create_index('idx_org_deleted', 'sys_organizations', ['deleted_at', 'tenant_id'], unique=False)
    op.add_column('sys_tenants', sa.Column('slug', sa.String(length=100), nullable=True, comment='租户标识符'))
    op.add_column('sys_tenants', sa.Column('domain', sa.String(length=255), nullable=True, comment='自定义域名'))
    op.add_column('sys_tenants', sa.Column('subdomain', sa.String(length=100), nullable=True, comment='子域名'))
    op.add_column('sys_tenants', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'))
    op.add_column('sys_tenants', sa.Column('deleted_by', sa.String(length=50), nullable=True, comment='删除者ID'))
    op.create_index('idx_tenant_domain', 'sys_tenants', ['domain'], unique=False)
    op.create_index('idx_tenant_slug', 'sys_tenants', ['slug'], unique=False)
    op.create_index('idx_tenant_subdomain', 'sys_tenants', ['subdomain'], unique=False)
    op.create_index(op.f('ix_sys_tenants_domain'), 'sys_tenants', ['domain'], unique=True)
    op.create_index(op.f('ix_sys_tenants_slug'), 'sys_tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_sys_tenants_subdomain'), 'sys_tenants', ['subdomain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_tenants_subdomain'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_slug'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_domain'), table_name='sys_tenants')
    op.drop_index('idx_tenant_subdomain', table_name='sys_tenants')
    op.drop_index('idx_tenant_slug', table_name='sys_tenants')
    op.drop_index('idx_tenant_domain', table_name='sys_tenants')
    op.drop_column('sys_tenants', 'deleted_by')
    op.drop_column('sys_tenants', 'deleted_at')
    op.drop_column('sys_tenants', 'subdomain')
    op.drop_column('sys_tenants', 'domain')
    op.drop_column('sys_tenants', 'slug')
    op.drop_index('idx_org_deleted', table_name='sys_organizations')
    op.drop_column('sys_organizations', 'deleted_by')
    op.drop_column('sys_organizations', 'deleted_at')
    # ### end Alembic commands ###
