"""initial migration with all models

Revision ID: 1629e80dd704
Revises: 
Create Date: 2025-08-16 02:06:38.380525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1629e80dd704'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_api_tokens',
    sa.Column('id', sa.String(length=50), nullable=False, comment='唯一标识'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('tenant_id', sa.String(length=50), nullable=True, comment='租户ID'),
    sa.Column('token_name', sa.String(length=100), nullable=False, comment='令牌名称'),
    sa.Column('token_key', sa.String(length=255), nullable=False, comment='令牌哈希值'),
    sa.Column('token_prefix', sa.String(length=10), nullable=False, comment='令牌前缀'),
    sa.Column('scopes', sa.JSON(), nullable=True, comment='令牌权限范围'),
    sa.Column('rate_limit', sa.Integer(), nullable=True, comment='速率限制'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间'),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True, comment='最后使用时间'),
    sa.Column('usage_count', sa.Integer(), nullable=True, comment='使用次数'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_prefix'),
    comment='API访问令牌表，管理第三方应用和API的访问凭证'
    )
    op.create_index('idx_token_active', 'sys_api_tokens', ['is_active', 'expires_at'], unique=False)
    op.create_index('idx_token_prefix', 'sys_api_tokens', ['token_prefix'], unique=False)
    op.create_index('idx_token_user_tenant', 'sys_api_tokens', ['user_id', 'tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_api_tokens_id'), 'sys_api_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_sys_api_tokens_tenant_id'), 'sys_api_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_api_tokens_token_key'), 'sys_api_tokens', ['token_key'], unique=True)
    op.create_index(op.f('ix_sys_api_tokens_user_id'), 'sys_api_tokens', ['user_id'], unique=False)
    op.create_table('sys_file_activities',
    sa.Column('id', sa.String(length=50), nullable=False, comment='活动记录唯一标识ID'),
    sa.Column('file_id', sa.String(length=50), nullable=False, comment='关联的文件ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='操作者用户ID'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='操作类型（upload/download/view/edit/delete/share）'),
    sa.Column('details', sa.Text(), nullable=True, comment='活动详细信息（JSON格式）'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='操作者IP地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='活动发生时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文件活动日志表，记录文件的所有操作和访问活动'
    )
    op.create_index('idx_activity_file_action', 'sys_file_activities', ['file_id', 'action'], unique=False)
    op.create_index('idx_activity_user_time', 'sys_file_activities', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sys_file_activities_action'), 'sys_file_activities', ['action'], unique=False)
    op.create_index(op.f('ix_sys_file_activities_created_at'), 'sys_file_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_file_activities_file_id'), 'sys_file_activities', ['file_id'], unique=False)
    op.create_index(op.f('ix_sys_file_activities_id'), 'sys_file_activities', ['id'], unique=False)
    op.create_table('sys_file_categories',
    sa.Column('id', sa.String(length=50), nullable=False, comment='分类唯一标识ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='分类名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='分类描述信息'),
    sa.Column('color', sa.String(length=7), nullable=True, comment='分类颜色（HEX格式）'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='分类图标名称'),
    sa.Column('parent_id', sa.String(length=50), nullable=True, comment='父分类ID（为空表示顶级分类）'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='分类完整路径'),
    sa.Column('level', sa.Integer(), nullable=False, comment='分类层级深度（0为顶级）'),
    sa.Column('owner_id', sa.String(length=50), nullable=False, comment='分类创建者用户ID'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统预设分类'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='分类是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='分类创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='分类最后更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文件分类表，管理文件的分类体系'
    )
    op.create_index('idx_category_owner_name', 'sys_file_categories', ['owner_id', 'name'], unique=False)
    op.create_index('idx_category_path', 'sys_file_categories', ['path'], unique=False)
    op.create_index(op.f('ix_sys_file_categories_id'), 'sys_file_categories', ['id'], unique=False)
    op.create_index(op.f('ix_sys_file_categories_name'), 'sys_file_categories', ['name'], unique=False)
    op.create_index(op.f('ix_sys_file_categories_owner_id'), 'sys_file_categories', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sys_file_categories_parent_id'), 'sys_file_categories', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_file_categories_path'), 'sys_file_categories', ['path'], unique=False)
    op.create_table('sys_file_comments',
    sa.Column('id', sa.String(length=50), nullable=False, comment='评论唯一标识ID'),
    sa.Column('file_id', sa.String(length=50), nullable=False, comment='关联的文件ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='评论者用户ID'),
    sa.Column('parent_id', sa.String(length=50), nullable=True, comment='父评论 ID（用于回复功能）'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论文本内容'),
    sa.Column('is_edited', sa.Boolean(), nullable=False, comment='是否被编辑过'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='评论创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='评论最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文件评论表，管理文件的评论和回复功能'
    )
    op.create_index(op.f('ix_sys_file_comments_file_id'), 'sys_file_comments', ['file_id'], unique=False)
    op.create_index(op.f('ix_sys_file_comments_id'), 'sys_file_comments', ['id'], unique=False)
    op.create_table('sys_file_shares',
    sa.Column('id', sa.UUID(), nullable=False, comment='文件分享记录ID'),
    sa.Column('file_id', sa.String(length=50), nullable=False, comment='关联的文件ID'),
    sa.Column('shared_by', sa.String(length=50), nullable=False, comment='分享者用户ID'),
    sa.Column('shared_with', sa.String(length=50), nullable=True, comment='分享接收者用户ID（为空表示公开分享）'),
    sa.Column('access_type', sa.String(length=20), nullable=False, comment='访问权限类型（read/write/admin）'),
    sa.Column('share_token', sa.String(length=64), nullable=True, comment='分享链接访问令牌'),
    sa.Column('password_protected', sa.Boolean(), nullable=False, comment='是否设置密码保护'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='分享密码哈希值'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='分享链接过期时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='分享是否有效'),
    sa.Column('access_count', sa.Integer(), nullable=False, comment='分享链接访问次数'),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True, comment='最后访问时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='分享创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='分享更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token'),
    comment='文件分享表，管理文件分享功能和权限控制'
    )
    op.create_index(op.f('ix_sys_file_shares_file_id'), 'sys_file_shares', ['file_id'], unique=False)
    op.create_index(op.f('ix_sys_file_shares_id'), 'sys_file_shares', ['id'], unique=False)
    op.create_table('sys_file_tag_relations',
    sa.Column('id', sa.String(length=50), nullable=False, comment='关联关系唯一标识ID'),
    sa.Column('file_id', sa.String(length=50), nullable=False, comment='关联的文件ID'),
    sa.Column('tag_id', sa.String(length=50), nullable=False, comment='关联的标签ID'),
    sa.Column('created_by', sa.String(length=50), nullable=False, comment='关联创建者用户ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='关联创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文件标签关联表，管理文件和标签的多对多关联'
    )
    op.create_index('idx_file_tag_unique', 'sys_file_tag_relations', ['file_id', 'tag_id'], unique=True)
    op.create_index(op.f('ix_sys_file_tag_relations_file_id'), 'sys_file_tag_relations', ['file_id'], unique=False)
    op.create_index(op.f('ix_sys_file_tag_relations_id'), 'sys_file_tag_relations', ['id'], unique=False)
    op.create_index(op.f('ix_sys_file_tag_relations_tag_id'), 'sys_file_tag_relations', ['tag_id'], unique=False)
    op.create_table('sys_file_tags',
    sa.Column('id', sa.String(length=50), nullable=False, comment='标签唯一标识ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='标签名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='标签描述信息'),
    sa.Column('color', sa.String(length=7), nullable=True, comment='标签颜色（HEX格式）'),
    sa.Column('owner_id', sa.String(length=50), nullable=False, comment='标签创建者用户ID'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统预设标签'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='标签使用次数统计'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='标签创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='标签最后更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文件标签表，管理文件的标签系统'
    )
    op.create_index('idx_tag_owner_name', 'sys_file_tags', ['owner_id', 'name'], unique=False)
    op.create_index('idx_tag_usage', 'sys_file_tags', ['usage_count'], unique=False)
    op.create_index(op.f('ix_sys_file_tags_id'), 'sys_file_tags', ['id'], unique=False)
    op.create_index(op.f('ix_sys_file_tags_name'), 'sys_file_tags', ['name'], unique=False)
    op.create_index(op.f('ix_sys_file_tags_owner_id'), 'sys_file_tags', ['owner_id'], unique=False)
    op.create_table('sys_file_versions',
    sa.Column('id', sa.UUID(), nullable=False, comment='文件版本记录ID'),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('file_id', sa.String(length=50), nullable=False, comment='关联的文件ID'),
    sa.Column('version_number', sa.Integer(), nullable=False, comment='版本号（从1开始递增）'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='版本文件存储名称'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='版本文件在MinIO中的存储路径'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='版本文件大小（字节）'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='版本文件SHA256哈希值'),
    sa.Column('change_description', sa.Text(), nullable=True, comment='版本变更描述'),
    sa.Column('created_by', sa.String(length=50), nullable=False, comment='版本创建者用户ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='版本创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文件版本管理表，记录文件的历史版本信息'
    )
    op.create_index('idx_version_file_number', 'sys_file_versions', ['file_id', 'version_number'], unique=False)
    op.create_index('idx_version_tenant', 'sys_file_versions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_file_versions_file_id'), 'sys_file_versions', ['file_id'], unique=False)
    op.create_index(op.f('ix_sys_file_versions_id'), 'sys_file_versions', ['id'], unique=False)
    op.create_index(op.f('ix_sys_file_versions_tenant_id'), 'sys_file_versions', ['tenant_id'], unique=False)
    op.create_table('sys_files',
    sa.Column('id', sa.UUID(), nullable=False, comment='文件唯一标识ID'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='用户上传时的原始文件名'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='系统生成的存储文件名（UUID）'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件在MinIO对象存储中的完整路径'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小（字节）'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='文件类型分类（document/image/video等）'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='文件MIME类型（application/pdf等）'),
    sa.Column('file_extension', sa.String(length=20), nullable=True, comment='文件扩展名（不含点号）'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='文件标题（用户自定义）'),
    sa.Column('description', sa.Text(), nullable=True, comment='文件描述信息'),
    sa.Column('tags', sa.Text(), nullable=True, comment='文件标签列表（JSON格式存储）'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='文件自定义分类'),
    sa.Column('keywords', sa.Text(), nullable=True, comment='文件搜索关键词（用于全文搜索）'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='文件SHA256哈希值，用于完整性校验和去重'),
    sa.Column('version', sa.Integer(), nullable=False, comment='文件版本号，从1开始递增'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='文件当前状态（active/deleted/archived等）'),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='文件可见性级别（private/internal/shared/public）'),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('owner_id', sa.String(length=50), nullable=False, comment='文件所有者用户ID'),
    sa.Column('parent_folder_id', sa.String(length=50), nullable=True, comment='父文件夹ID（null表示根目录）'),
    sa.Column('download_count', sa.Integer(), nullable=False, comment='文件下载次数统计'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='文件查看次数统计'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='文件创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='文件最后更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='文件删除时间（软删除）'),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True, comment='文件最后访问时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name'),
    comment='文件主表，存储所有文件的基本信息和元数据'
    )
    op.create_index('idx_file_created', 'sys_files', ['created_at'], unique=False)
    op.create_index('idx_file_hash', 'sys_files', ['file_hash'], unique=False)
    op.create_index('idx_file_owner_status', 'sys_files', ['owner_id', 'status'], unique=False)
    op.create_index('idx_file_tenant_category', 'sys_files', ['tenant_id', 'category'], unique=False)
    op.create_index('idx_file_tenant_owner', 'sys_files', ['tenant_id', 'owner_id'], unique=False)
    op.create_index('idx_file_type_status', 'sys_files', ['file_type', 'status'], unique=False)
    op.create_index(op.f('ix_sys_files_category'), 'sys_files', ['category'], unique=False)
    op.create_index(op.f('ix_sys_files_created_at'), 'sys_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_files_file_extension'), 'sys_files', ['file_extension'], unique=False)
    op.create_index(op.f('ix_sys_files_file_hash'), 'sys_files', ['file_hash'], unique=False)
    op.create_index(op.f('ix_sys_files_file_type'), 'sys_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_sys_files_id'), 'sys_files', ['id'], unique=False)
    op.create_index(op.f('ix_sys_files_original_name'), 'sys_files', ['original_name'], unique=False)
    op.create_index(op.f('ix_sys_files_owner_id'), 'sys_files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sys_files_parent_folder_id'), 'sys_files', ['parent_folder_id'], unique=False)
    op.create_index(op.f('ix_sys_files_status'), 'sys_files', ['status'], unique=False)
    op.create_index(op.f('ix_sys_files_tenant_id'), 'sys_files', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_files_title'), 'sys_files', ['title'], unique=False)
    op.create_index(op.f('ix_sys_files_visibility'), 'sys_files', ['visibility'], unique=False)
    op.create_table('sys_folders',
    sa.Column('id', sa.String(length=50), nullable=False, comment='文件夹唯一标识ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='文件夹名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='文件夹描述信息'),
    sa.Column('parent_id', sa.String(length=50), nullable=True, comment='父文件夹ID（null表示根目录）'),
    sa.Column('path', sa.String(length=1000), nullable=False, comment='文件夹完整路径（/root/folder1/folder2）'),
    sa.Column('level', sa.Integer(), nullable=False, comment='文件夹层级深度（0为根目录）'),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('owner_id', sa.String(length=50), nullable=False, comment='文件夹所有者用户ID'),
    sa.Column('visibility', sa.String(length=20), nullable=False, comment='文件夹可见性级别'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统预定义文件夹（不可删除）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='文件夹创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='文件夹最后更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文件夹表，管理文件的层级组织结构'
    )
    op.create_index('idx_folder_owner_parent', 'sys_folders', ['owner_id', 'parent_id'], unique=False)
    op.create_index('idx_folder_path', 'sys_folders', ['path'], unique=False)
    op.create_index('idx_folder_tenant_owner', 'sys_folders', ['tenant_id', 'owner_id'], unique=False)
    op.create_index(op.f('ix_sys_folders_id'), 'sys_folders', ['id'], unique=False)
    op.create_index(op.f('ix_sys_folders_name'), 'sys_folders', ['name'], unique=False)
    op.create_index(op.f('ix_sys_folders_owner_id'), 'sys_folders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sys_folders_parent_id'), 'sys_folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_folders_path'), 'sys_folders', ['path'], unique=False)
    op.create_index(op.f('ix_sys_folders_tenant_id'), 'sys_folders', ['tenant_id'], unique=False)
    op.create_table('sys_group_permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('group_id', sa.String(length=50), nullable=False, comment='用户组ID'),
    sa.Column('permission_id', sa.String(length=50), nullable=False, comment='权限ID'),
    sa.Column('granted_by', sa.String(length=50), nullable=True, comment='授权人'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='授权时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='组权限关联表，管理用户组与权限的多对多关系'
    )
    op.create_index('idx_group_perm_tenant', 'sys_group_permission', ['tenant_id', 'group_id'], unique=False)
    op.create_index('idx_group_perm_unique', 'sys_group_permission', ['group_id', 'permission_id'], unique=True)
    op.create_index(op.f('ix_sys_group_permission_group_id'), 'sys_group_permission', ['group_id'], unique=False)
    op.create_index(op.f('ix_sys_group_permission_permission_id'), 'sys_group_permission', ['permission_id'], unique=False)
    op.create_index(op.f('ix_sys_group_permission_tenant_id'), 'sys_group_permission', ['tenant_id'], unique=False)
    op.create_table('sys_group_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('group_id', sa.String(length=50), nullable=False, comment='用户组ID'),
    sa.Column('role_id', sa.String(length=50), nullable=False, comment='角色ID'),
    sa.Column('granted_by', sa.String(length=50), nullable=True, comment='授权人'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='授权时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='组角色关联表，管理用户组与角色的多对多关系'
    )
    op.create_index('idx_group_role_tenant', 'sys_group_role', ['tenant_id', 'group_id'], unique=False)
    op.create_index('idx_group_role_unique', 'sys_group_role', ['group_id', 'role_id'], unique=True)
    op.create_index(op.f('ix_sys_group_role_group_id'), 'sys_group_role', ['group_id'], unique=False)
    op.create_index(op.f('ix_sys_group_role_role_id'), 'sys_group_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_sys_group_role_tenant_id'), 'sys_group_role', ['tenant_id'], unique=False)
    op.create_table('sys_invitations',
    sa.Column('id', sa.UUID(), nullable=False, comment='邀请ID'),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('organization_id', sa.String(length=50), nullable=True, comment='组织ID'),
    sa.Column('team_id', sa.String(length=50), nullable=True, comment='团队ID'),
    sa.Column('inviter_id', sa.String(length=50), nullable=False, comment='邀请人ID'),
    sa.Column('invitee_id', sa.String(length=50), nullable=True, comment='被邀请人ID'),
    sa.Column('invitee_email', sa.String(length=255), nullable=False, comment='被邀请人邮箱'),
    sa.Column('invite_type', sa.String(length=20), nullable=True, comment='邀请类型'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='被邀请的角色'),
    sa.Column('permissions', sa.JSON(), nullable=True, comment='邀请权限'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='邀请状态'),
    sa.Column('token', sa.String(length=100), nullable=False, comment='邀请令牌'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='邀请管理表，用于邀请用户加入组织或团队'
    )
    op.create_index('idx_invitation_email_status', 'sys_invitations', ['invitee_email', 'status'], unique=False)
    op.create_index('idx_invitation_expires', 'sys_invitations', ['expires_at', 'status'], unique=False)
    op.create_index('idx_invitation_tenant_org', 'sys_invitations', ['tenant_id', 'organization_id'], unique=False)
    op.create_index(op.f('ix_sys_invitations_invitee_email'), 'sys_invitations', ['invitee_email'], unique=False)
    op.create_index(op.f('ix_sys_invitations_invitee_id'), 'sys_invitations', ['invitee_id'], unique=False)
    op.create_index(op.f('ix_sys_invitations_inviter_id'), 'sys_invitations', ['inviter_id'], unique=False)
    op.create_index(op.f('ix_sys_invitations_organization_id'), 'sys_invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sys_invitations_team_id'), 'sys_invitations', ['team_id'], unique=False)
    op.create_index(op.f('ix_sys_invitations_tenant_id'), 'sys_invitations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_invitations_token'), 'sys_invitations', ['token'], unique=True)
    op.create_table('sys_login_history',
    sa.Column('id', sa.String(length=50), nullable=False, comment='唯一标识'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('tenant_id', sa.String(length=50), nullable=True, comment='登录租户ID'),
    sa.Column('session_id', sa.String(length=100), nullable=True, comment='会话ID'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='登录IP地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理'),
    sa.Column('device_info', sa.JSON(), nullable=True, comment='设备信息'),
    sa.Column('login_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='登录时间'),
    sa.Column('logout_timestamp', sa.DateTime(timezone=True), nullable=True, comment='登出时间'),
    sa.Column('is_success', sa.Boolean(), nullable=False, comment='是否登录成功'),
    sa.Column('failure_reason', sa.String(length=255), nullable=True, comment='登录失败原因'),
    sa.Column('login_method', sa.String(length=20), nullable=True, comment='登录方式'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户登录历史表，记录用户登录登出行为和安全审计信息'
    )
    op.create_index('idx_login_ip', 'sys_login_history', ['ip_address', 'login_timestamp'], unique=False)
    op.create_index('idx_login_tenant_time', 'sys_login_history', ['tenant_id', 'login_timestamp'], unique=False)
    op.create_index('idx_login_user_time', 'sys_login_history', ['user_id', 'login_timestamp'], unique=False)
    op.create_index(op.f('ix_sys_login_history_id'), 'sys_login_history', ['id'], unique=False)
    op.create_index(op.f('ix_sys_login_history_session_id'), 'sys_login_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_sys_login_history_tenant_id'), 'sys_login_history', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_login_history_user_id'), 'sys_login_history', ['user_id'], unique=False)
    op.create_table('sys_org_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('organization_id', sa.String(length=50), nullable=False, comment='组织ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='操作用户ID'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='操作类型'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='资源类型'),
    sa.Column('resource_id', sa.String(length=100), nullable=True, comment='资源ID'),
    sa.Column('details', sa.JSON(), nullable=True, comment='操作详情JSON'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='操作IP'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='组织活动日志表，记录组织内的重要操作和变更'
    )
    op.create_index('idx_org_activity_action', 'sys_org_activities', ['action', 'created_at'], unique=False)
    op.create_index('idx_org_activity_tenant', 'sys_org_activities', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_org_activity_time', 'sys_org_activities', ['organization_id', 'created_at'], unique=False)
    op.create_index('idx_org_activity_user', 'sys_org_activities', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sys_org_activities_id'), 'sys_org_activities', ['id'], unique=False)
    op.create_index(op.f('ix_sys_org_activities_organization_id'), 'sys_org_activities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sys_org_activities_tenant_id'), 'sys_org_activities', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_org_activities_user_id'), 'sys_org_activities', ['user_id'], unique=False)
    op.create_table('sys_organizations',
    sa.Column('id', sa.String(length=50), nullable=False, comment='组织唯一标识'),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='所属租户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='组织名称'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='组织显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='组织描述'),
    sa.Column('logo_url', sa.String(length=255), nullable=True, comment='组织Logo URL'),
    sa.Column('owner_id', sa.String(length=50), nullable=False, comment='组织所有者ID'),
    sa.Column('parent_id', sa.String(length=50), nullable=True, comment='父组织ID'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='组织层级路径'),
    sa.Column('level', sa.Integer(), nullable=False, comment='组织层级'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='组织是否激活'),
    sa.Column('settings', sa.JSON(), nullable=True, comment='组织配置'),
    sa.Column('member_count', sa.Integer(), nullable=True, comment='成员数量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='组织架构表，管理公司的层级组织结构'
    )
    op.create_index('idx_org_owner', 'sys_organizations', ['owner_id'], unique=False)
    op.create_index('idx_org_parent_path', 'sys_organizations', ['parent_id', 'path'], unique=False)
    op.create_index('idx_org_tenant_name', 'sys_organizations', ['tenant_id', 'name'], unique=True)
    op.create_index(op.f('ix_sys_organizations_id'), 'sys_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_sys_organizations_name'), 'sys_organizations', ['name'], unique=False)
    op.create_index(op.f('ix_sys_organizations_owner_id'), 'sys_organizations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sys_organizations_parent_id'), 'sys_organizations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_organizations_path'), 'sys_organizations', ['path'], unique=False)
    op.create_index(op.f('ix_sys_organizations_tenant_id'), 'sys_organizations', ['tenant_id'], unique=False)
    op.create_table('sys_permissions',
    sa.Column('id', sa.String(length=50), nullable=False, comment='权限唯一标识'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='权限名称（如user:create）'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='权限显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='权限描述'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='权限分类'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='资源类型'),
    sa.Column('action', sa.String(length=50), nullable=True, comment='操作类型'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统权限'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='权限是否激活'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.String(length=50), nullable=True, comment='删除者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='权限表，管理系统中的所有权限定义'
    )
    op.create_index('idx_permission_category_action', 'sys_permissions', ['category', 'action'], unique=False)
    op.create_index('idx_permission_resource_action', 'sys_permissions', ['resource_type', 'action'], unique=False)
    op.create_index(op.f('ix_sys_permissions_action'), 'sys_permissions', ['action'], unique=False)
    op.create_index(op.f('ix_sys_permissions_category'), 'sys_permissions', ['category'], unique=False)
    op.create_index(op.f('ix_sys_permissions_id'), 'sys_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_sys_permissions_name'), 'sys_permissions', ['name'], unique=True)
    op.create_index(op.f('ix_sys_permissions_resource_type'), 'sys_permissions', ['resource_type'], unique=False)
    op.create_table('sys_role_permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('role_id', sa.String(length=50), nullable=False, comment='角色ID'),
    sa.Column('permission_id', sa.String(length=50), nullable=False, comment='权限ID'),
    sa.Column('granted_by', sa.String(length=50), nullable=True, comment='授权人'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='授权时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色权限关联表，管理角色与权限的多对多关系'
    )
    op.create_index('idx_role_perm_tenant', 'sys_role_permission', ['tenant_id', 'role_id'], unique=False)
    op.create_index('idx_role_perm_unique', 'sys_role_permission', ['role_id', 'permission_id'], unique=True)
    op.create_index(op.f('ix_sys_role_permission_permission_id'), 'sys_role_permission', ['permission_id'], unique=False)
    op.create_index(op.f('ix_sys_role_permission_role_id'), 'sys_role_permission', ['role_id'], unique=False)
    op.create_index(op.f('ix_sys_role_permission_tenant_id'), 'sys_role_permission', ['tenant_id'], unique=False)
    op.create_table('sys_roles',
    sa.Column('id', sa.String(length=50), nullable=False, comment='角色唯一标识'),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='角色显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色描述'),
    sa.Column('role_type', sa.String(length=20), nullable=False, comment='角色类型'),
    sa.Column('level', sa.Integer(), nullable=False, comment='角色权限级别（数值越大权限越高）'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统角色'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为默认角色'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='角色是否激活'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.String(length=50), nullable=True, comment='删除者ID'),
    sa.Column('settings', sa.JSON(), nullable=True, comment='角色配置信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表，管理系统中的角色信息和权限级别'
    )
    op.create_index('idx_role_tenant_name', 'sys_roles', ['tenant_id', 'name'], unique=True)
    op.create_index('idx_role_type_level', 'sys_roles', ['role_type', 'level'], unique=False)
    op.create_index(op.f('ix_sys_roles_id'), 'sys_roles', ['id'], unique=False)
    op.create_index(op.f('ix_sys_roles_name'), 'sys_roles', ['name'], unique=False)
    op.create_index(op.f('ix_sys_roles_tenant_id'), 'sys_roles', ['tenant_id'], unique=False)
    op.create_table('sys_teams',
    sa.Column('id', sa.String(length=50), nullable=False, comment='团队唯一标识'),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='所属租户ID'),
    sa.Column('organization_id', sa.String(length=50), nullable=False, comment='所属组织ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='团队名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='团队描述'),
    sa.Column('creator_id', sa.String(length=50), nullable=False, comment='创建者ID'),
    sa.Column('parent_id', sa.String(length=50), nullable=True, comment='父团队ID'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='团队层级路径'),
    sa.Column('level', sa.Integer(), nullable=False, comment='团队层级'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='团队是否激活'),
    sa.Column('settings', sa.JSON(), nullable=True, comment='团队配置'),
    sa.Column('member_count', sa.Integer(), nullable=True, comment='成员数量'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='团队管理表，管理组织内部的项目或职能团队'
    )
    op.create_index('idx_team_org_name', 'sys_teams', ['organization_id', 'name'], unique=True)
    op.create_index('idx_team_parent_path', 'sys_teams', ['parent_id', 'path'], unique=False)
    op.create_index('idx_team_tenant', 'sys_teams', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_teams_id'), 'sys_teams', ['id'], unique=False)
    op.create_index(op.f('ix_sys_teams_name'), 'sys_teams', ['name'], unique=False)
    op.create_index(op.f('ix_sys_teams_organization_id'), 'sys_teams', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sys_teams_parent_id'), 'sys_teams', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_teams_path'), 'sys_teams', ['path'], unique=False)
    op.create_index(op.f('ix_sys_teams_tenant_id'), 'sys_teams', ['tenant_id'], unique=False)
    op.create_table('sys_tenant_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.String(length=50), nullable=True, comment='操作用户ID'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='操作类型'),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='资源类型'),
    sa.Column('resource_id', sa.String(length=100), nullable=True, comment='资源ID'),
    sa.Column('details', sa.JSON(), nullable=True, comment='操作详情JSON'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='操作IP'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='租户活动日志表，记录租户级别的重要操作和变更'
    )
    op.create_index('idx_tenant_activity_action', 'sys_tenant_activities', ['action', 'created_at'], unique=False)
    op.create_index('idx_tenant_activity_time', 'sys_tenant_activities', ['tenant_id', 'created_at'], unique=False)
    op.create_index('idx_tenant_activity_user', 'sys_tenant_activities', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sys_tenant_activities_id'), 'sys_tenant_activities', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_activities_tenant_id'), 'sys_tenant_activities', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_activities_user_id'), 'sys_tenant_activities', ['user_id'], unique=False)
    op.create_table('sys_tenant_databases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('connection_config', sa.JSON(), nullable=False, comment='数据库连接配置(JSON加密存储)'),
    sa.Column('connection_pool_config', sa.JSON(), nullable=True, comment='连接池配置'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True, comment='最后健康检查时间'),
    sa.Column('health_status', sa.String(length=20), nullable=True, comment='健康状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='租户数据库配置表，存储每个租户的数据库连接和健康状态信息'
    )
    op.create_index('idx_tenant_db_status', 'sys_tenant_databases', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_sys_tenant_databases_id'), 'sys_tenant_databases', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_databases_tenant_id'), 'sys_tenant_databases', ['tenant_id'], unique=True)
    op.create_table('sys_tenant_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='用户在租户中的角色'),
    sa.Column('permissions', sa.JSON(), nullable=True, comment='用户在租户中的权限'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='是否为租户管理员'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='关联是否激活'),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='加入时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='租户用户关联表，管理用户与租户的多对多关联和权限'
    )
    op.create_index('idx_tenant_role', 'sys_tenant_users', ['tenant_id', 'role'], unique=False)
    op.create_index('idx_tenant_user_unique', 'sys_tenant_users', ['tenant_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_sys_tenant_users_id'), 'sys_tenant_users', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_users_tenant_id'), 'sys_tenant_users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_users_user_id'), 'sys_tenant_users', ['user_id'], unique=False)
    op.create_table('sys_tenants',
    sa.Column('id', sa.String(length=50), nullable=False, comment='租户唯一标识'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='租户名称'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='租户显示名称'),
    sa.Column('schema_name', sa.String(length=100), nullable=False, comment='数据库Schema名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='租户描述'),
    sa.Column('owner_id', sa.String(length=50), nullable=False, comment='租户所有者ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='租户状态'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='租户是否激活'),
    sa.Column('settings', sa.JSON(), nullable=True, comment='租户配置'),
    sa.Column('features', sa.JSON(), nullable=True, comment='开启的功能列表'),
    sa.Column('limits', sa.JSON(), nullable=True, comment='租户限制配置'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='租户主表，存储多租户系统中的租户信息和配置'
    )
    op.create_index('idx_tenant_owner', 'sys_tenants', ['owner_id'], unique=False)
    op.create_index('idx_tenant_status', 'sys_tenants', ['status', 'is_active'], unique=False)
    op.create_index(op.f('ix_sys_tenants_id'), 'sys_tenants', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenants_name'), 'sys_tenants', ['name'], unique=True)
    op.create_index(op.f('ix_sys_tenants_owner_id'), 'sys_tenants', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sys_tenants_schema_name'), 'sys_tenants', ['schema_name'], unique=True)
    op.create_table('sys_user_activities',
    sa.Column('id', sa.String(length=50), nullable=False, comment='唯一标识'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='活动主体用户ID'),
    sa.Column('tenant_id', sa.String(length=50), nullable=True, comment='租户ID'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='活动类型'),
    sa.Column('target_type', sa.String(length=50), nullable=True, comment='操作对象类型'),
    sa.Column('target_id', sa.String(length=255), nullable=True, comment='操作对象ID'),
    sa.Column('details', sa.JSON(), nullable=True, comment='活动详情JSON'),
    sa.Column('actor_id', sa.String(length=50), nullable=True, comment='操作者ID'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='操作IP'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户活动日志表，记录用户的关键操作和行为'
    )
    op.create_index('idx_user_activity_action', 'sys_user_activities', ['action', 'created_at'], unique=False)
    op.create_index('idx_user_activity_tenant_time', 'sys_user_activities', ['user_id', 'tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sys_user_activities_actor_id'), 'sys_user_activities', ['actor_id'], unique=False)
    op.create_index(op.f('ix_sys_user_activities_id'), 'sys_user_activities', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_activities_tenant_id'), 'sys_user_activities', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_user_activities_user_id'), 'sys_user_activities', ['user_id'], unique=False)
    op.create_table('sys_user_group',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('group_id', sa.String(length=50), nullable=False, comment='用户组ID'),
    sa.Column('added_by', sa.String(length=50), nullable=True, comment='添加人'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='添加时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户组关联表，管理用户与用户组的多对多关系'
    )
    op.create_index('idx_user_group_tenant', 'sys_user_group', ['tenant_id', 'user_id'], unique=False)
    op.create_index('idx_user_group_unique', 'sys_user_group', ['user_id', 'group_id'], unique=True)
    op.create_index(op.f('ix_sys_user_group_group_id'), 'sys_user_group', ['group_id'], unique=False)
    op.create_index(op.f('ix_sys_user_group_tenant_id'), 'sys_user_group', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_user_group_user_id'), 'sys_user_group', ['user_id'], unique=False)
    op.create_table('sys_user_groups',
    sa.Column('id', sa.String(length=50), nullable=False, comment='用户组唯一标识'),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='用户组名称'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='用户组显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='用户组描述'),
    sa.Column('parent_id', sa.String(length=50), nullable=True, comment='父用户组ID'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='用户组层级路径'),
    sa.Column('level', sa.Integer(), nullable=False, comment='用户组层级'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='是否为系统用户组'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='用户组是否激活'),
    sa.Column('member_count', sa.Integer(), nullable=True, comment='成员数量'),
    sa.Column('owner_id', sa.String(length=50), nullable=False, comment='用户组创建者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户组表，管理用户的分组和批量权限管理'
    )
    op.create_index('idx_group_parent_path', 'sys_user_groups', ['parent_id', 'path'], unique=False)
    op.create_index('idx_group_tenant_name', 'sys_user_groups', ['tenant_id', 'name'], unique=True)
    op.create_index(op.f('ix_sys_user_groups_id'), 'sys_user_groups', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_groups_name'), 'sys_user_groups', ['name'], unique=False)
    op.create_index(op.f('ix_sys_user_groups_owner_id'), 'sys_user_groups', ['owner_id'], unique=False)
    op.create_index(op.f('ix_sys_user_groups_parent_id'), 'sys_user_groups', ['parent_id'], unique=False)
    op.create_index(op.f('ix_sys_user_groups_path'), 'sys_user_groups', ['path'], unique=False)
    op.create_index(op.f('ix_sys_user_groups_tenant_id'), 'sys_user_groups', ['tenant_id'], unique=False)
    op.create_table('sys_user_organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('organization_id', sa.String(length=50), nullable=False, comment='组织ID'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='用户在组织中的角色'),
    sa.Column('permissions', sa.JSON(), nullable=True, comment='用户在组织中的权限'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='是否为组织管理员'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='关联是否激活'),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='加入时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户组织关系表，管理用户与组织的多对多关联'
    )
    op.create_index('idx_user_org_role', 'sys_user_organization', ['organization_id', 'role'], unique=False)
    op.create_index('idx_user_org_tenant', 'sys_user_organization', ['tenant_id', 'organization_id'], unique=False)
    op.create_index('idx_user_org_unique', 'sys_user_organization', ['user_id', 'organization_id'], unique=True)
    op.create_index(op.f('ix_sys_user_organization_id'), 'sys_user_organization', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_organization_organization_id'), 'sys_user_organization', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sys_user_organization_tenant_id'), 'sys_user_organization', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_user_organization_user_id'), 'sys_user_organization', ['user_id'], unique=False)
    op.create_table('sys_user_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('permission_id', sa.String(length=50), nullable=False, comment='权限ID'),
    sa.Column('resource_id', sa.String(length=100), nullable=True, comment='资源ID（特定资源权限）'),
    sa.Column('granted', sa.Boolean(), nullable=False, comment='是否授予（True）或拒绝（False）'),
    sa.Column('granted_by', sa.String(length=50), nullable=True, comment='授权人ID'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='授权时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='权限过期时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='权限是否激活'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户权限表，管理直接授予用户的权限'
    )
    op.create_index('idx_user_perm_tenant', 'sys_user_permissions', ['tenant_id', 'user_id'], unique=False)
    op.create_index('idx_user_perm_unique', 'sys_user_permissions', ['user_id', 'permission_id', 'resource_id'], unique=True)
    op.create_index(op.f('ix_sys_user_permissions_id'), 'sys_user_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_permissions_permission_id'), 'sys_user_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_sys_user_permissions_tenant_id'), 'sys_user_permissions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_user_permissions_user_id'), 'sys_user_permissions', ['user_id'], unique=False)
    op.create_table('sys_user_profiles',
    sa.Column('id', sa.String(length=50), nullable=False, comment='唯一标识'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='关联的用户ID'),
    sa.Column('nickname', sa.String(length=100), nullable=True, comment='用户昵称/显示名'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='真实姓名'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号码'),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('bio', sa.Text(), nullable=True, comment='个人简介'),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True, comment='出生日期'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性别'),
    sa.Column('country', sa.String(length=50), nullable=True, comment='国家'),
    sa.Column('city', sa.String(length=50), nullable=True, comment='城市'),
    sa.Column('address', sa.Text(), nullable=True, comment='详细地址'),
    sa.Column('preferred_language', sa.String(length=10), nullable=True, comment='偏好语言'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='时区'),
    sa.Column('theme', sa.String(length=20), nullable=True, comment='主题偏好'),
    sa.Column('notification_settings', sa.JSON(), nullable=True, comment='通知设置'),
    sa.Column('privacy_settings', sa.JSON(), nullable=True, comment='隐私设置'),
    sa.Column('urls', sa.JSON(), nullable=True, comment='个人网站、社交媒体链接'),
    sa.Column('settings', sa.JSON(), nullable=True, comment='用户个性化设置'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户资料扩展表，存储用户的详细个人信息和偏好设置'
    )
    op.create_index(op.f('ix_sys_user_profiles_id'), 'sys_user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_profiles_user_id'), 'sys_user_profiles', ['user_id'], unique=True)
    op.create_table('sys_user_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.String(length=50), nullable=False, comment='角色ID'),
    sa.Column('granted_by', sa.String(length=50), nullable=True, comment='授权人'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='授权时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户角色关联表，管理用户与角色的多对多关系'
    )
    op.create_index('idx_user_role_tenant', 'sys_user_role', ['tenant_id', 'user_id'], unique=False)
    op.create_index('idx_user_role_unique', 'sys_user_role', ['user_id', 'role_id'], unique=True)
    op.create_index(op.f('ix_sys_user_role_role_id'), 'sys_user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_sys_user_role_tenant_id'), 'sys_user_role', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_user_role_user_id'), 'sys_user_role', ['user_id'], unique=False)
    op.create_table('sys_user_sessions',
    sa.Column('id', sa.String(length=50), nullable=False, comment='会话唯一标识'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('session_token', sa.String(length=500), nullable=False, comment='会话令牌'),
    sa.Column('refresh_token', sa.String(length=500), nullable=True, comment='刷新令牌'),
    sa.Column('device_info', sa.String(length=500), nullable=True, comment='设备信息'),
    sa.Column('device_id', sa.String(length=100), nullable=True, comment='设备标识'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='登录IP地址'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='会话过期时间'),
    sa.Column('last_used', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='最后使用时间'),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='最后活动时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='会话是否活跃'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户会话表，管理用户登录会话和状态'
    )
    op.create_index('idx_session_expires', 'sys_user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_session_token', 'sys_user_sessions', ['session_token'], unique=False)
    op.create_index('idx_session_user_active', 'sys_user_sessions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_sys_user_sessions_id'), 'sys_user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_sessions_refresh_token'), 'sys_user_sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_sys_user_sessions_session_token'), 'sys_user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_sys_user_sessions_user_id'), 'sys_user_sessions', ['user_id'], unique=False)
    op.create_table('sys_user_team',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('team_id', sa.String(length=50), nullable=False, comment='团队ID'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='用户在团队中的角色'),
    sa.Column('permissions', sa.JSON(), nullable=True, comment='用户在团队中的权限'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='关联是否激活'),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='加入时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户团队关系表，管理用户与团队的多对多关联'
    )
    op.create_index('idx_user_team_role', 'sys_user_team', ['team_id', 'role'], unique=False)
    op.create_index('idx_user_team_tenant', 'sys_user_team', ['tenant_id', 'team_id'], unique=False)
    op.create_index('idx_user_team_unique', 'sys_user_team', ['user_id', 'team_id'], unique=True)
    op.create_index(op.f('ix_sys_user_team_id'), 'sys_user_team', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_team_team_id'), 'sys_user_team', ['team_id'], unique=False)
    op.create_index(op.f('ix_sys_user_team_tenant_id'), 'sys_user_team', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_user_team_user_id'), 'sys_user_team', ['user_id'], unique=False)
    op.create_table('sys_user_verifications',
    sa.Column('id', sa.String(length=50), nullable=False, comment='唯一标识'),
    sa.Column('user_id', sa.String(length=50), nullable=True, comment='用户ID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='验证邮箱'),
    sa.Column('verification_type', sa.String(length=20), nullable=False, comment='验证类型（email_verify/password_reset）'),
    sa.Column('verification_code', sa.String(length=100), nullable=False, comment='验证码'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='验证码过期时间'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='使用时间'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='是否已使用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户验证表，管理邮箱验证和密码重置验证码'
    )
    op.create_index('idx_verification_code', 'sys_user_verifications', ['verification_code'], unique=False)
    op.create_index('idx_verification_email_type', 'sys_user_verifications', ['email', 'verification_type'], unique=False)
    op.create_index('idx_verification_expires', 'sys_user_verifications', ['expires_at', 'is_used'], unique=False)
    op.create_index(op.f('ix_sys_user_verifications_email'), 'sys_user_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_sys_user_verifications_id'), 'sys_user_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_verifications_user_id'), 'sys_user_verifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_sys_user_verifications_verification_code'), 'sys_user_verifications', ['verification_code'], unique=True)
    op.create_table('sys_users',
    sa.Column('id', sa.String(length=50), nullable=False, comment='用户唯一标识'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='电子邮箱'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='哈希密码'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='用户状态'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否为超级管理员'),
    sa.Column('is_staff', sa.Boolean(), nullable=False, comment='是否为员工'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='邮箱是否已验证'),
    sa.Column('roles', sa.JSON(), nullable=True, comment='用户角色列表（JSON格式存储）'),
    sa.Column('permissions', sa.JSON(), nullable=True, comment='用户权限列表（JSON格式存储）'),
    sa.Column('current_tenant_id', sa.String(length=50), nullable=True, comment='当前活跃租户ID'),
    sa.Column('tenant_ids', sa.JSON(), nullable=True, comment='用户所属的所有租户ID列表'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.Column('deleted_by', sa.String(length=50), nullable=True, comment='删除者ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户主表，存储核心用户信息和认证数据'
    )
    op.create_index(op.f('ix_sys_users_current_tenant_id'), 'sys_users', ['current_tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_users_email'), 'sys_users', ['email'], unique=True)
    op.create_index(op.f('ix_sys_users_id'), 'sys_users', ['id'], unique=False)
    op.create_index(op.f('ix_sys_users_username'), 'sys_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_users_username'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_id'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_email'), table_name='sys_users')
    op.drop_index(op.f('ix_sys_users_current_tenant_id'), table_name='sys_users')
    op.drop_table('sys_users')
    op.drop_index(op.f('ix_sys_user_verifications_verification_code'), table_name='sys_user_verifications')
    op.drop_index(op.f('ix_sys_user_verifications_user_id'), table_name='sys_user_verifications')
    op.drop_index(op.f('ix_sys_user_verifications_id'), table_name='sys_user_verifications')
    op.drop_index(op.f('ix_sys_user_verifications_email'), table_name='sys_user_verifications')
    op.drop_index('idx_verification_expires', table_name='sys_user_verifications')
    op.drop_index('idx_verification_email_type', table_name='sys_user_verifications')
    op.drop_index('idx_verification_code', table_name='sys_user_verifications')
    op.drop_table('sys_user_verifications')
    op.drop_index(op.f('ix_sys_user_team_user_id'), table_name='sys_user_team')
    op.drop_index(op.f('ix_sys_user_team_tenant_id'), table_name='sys_user_team')
    op.drop_index(op.f('ix_sys_user_team_team_id'), table_name='sys_user_team')
    op.drop_index(op.f('ix_sys_user_team_id'), table_name='sys_user_team')
    op.drop_index('idx_user_team_unique', table_name='sys_user_team')
    op.drop_index('idx_user_team_tenant', table_name='sys_user_team')
    op.drop_index('idx_user_team_role', table_name='sys_user_team')
    op.drop_table('sys_user_team')
    op.drop_index(op.f('ix_sys_user_sessions_user_id'), table_name='sys_user_sessions')
    op.drop_index(op.f('ix_sys_user_sessions_session_token'), table_name='sys_user_sessions')
    op.drop_index(op.f('ix_sys_user_sessions_refresh_token'), table_name='sys_user_sessions')
    op.drop_index(op.f('ix_sys_user_sessions_id'), table_name='sys_user_sessions')
    op.drop_index('idx_session_user_active', table_name='sys_user_sessions')
    op.drop_index('idx_session_token', table_name='sys_user_sessions')
    op.drop_index('idx_session_expires', table_name='sys_user_sessions')
    op.drop_table('sys_user_sessions')
    op.drop_index(op.f('ix_sys_user_role_user_id'), table_name='sys_user_role')
    op.drop_index(op.f('ix_sys_user_role_tenant_id'), table_name='sys_user_role')
    op.drop_index(op.f('ix_sys_user_role_role_id'), table_name='sys_user_role')
    op.drop_index('idx_user_role_unique', table_name='sys_user_role')
    op.drop_index('idx_user_role_tenant', table_name='sys_user_role')
    op.drop_table('sys_user_role')
    op.drop_index(op.f('ix_sys_user_profiles_user_id'), table_name='sys_user_profiles')
    op.drop_index(op.f('ix_sys_user_profiles_id'), table_name='sys_user_profiles')
    op.drop_table('sys_user_profiles')
    op.drop_index(op.f('ix_sys_user_permissions_user_id'), table_name='sys_user_permissions')
    op.drop_index(op.f('ix_sys_user_permissions_tenant_id'), table_name='sys_user_permissions')
    op.drop_index(op.f('ix_sys_user_permissions_permission_id'), table_name='sys_user_permissions')
    op.drop_index(op.f('ix_sys_user_permissions_id'), table_name='sys_user_permissions')
    op.drop_index('idx_user_perm_unique', table_name='sys_user_permissions')
    op.drop_index('idx_user_perm_tenant', table_name='sys_user_permissions')
    op.drop_table('sys_user_permissions')
    op.drop_index(op.f('ix_sys_user_organization_user_id'), table_name='sys_user_organization')
    op.drop_index(op.f('ix_sys_user_organization_tenant_id'), table_name='sys_user_organization')
    op.drop_index(op.f('ix_sys_user_organization_organization_id'), table_name='sys_user_organization')
    op.drop_index(op.f('ix_sys_user_organization_id'), table_name='sys_user_organization')
    op.drop_index('idx_user_org_unique', table_name='sys_user_organization')
    op.drop_index('idx_user_org_tenant', table_name='sys_user_organization')
    op.drop_index('idx_user_org_role', table_name='sys_user_organization')
    op.drop_table('sys_user_organization')
    op.drop_index(op.f('ix_sys_user_groups_tenant_id'), table_name='sys_user_groups')
    op.drop_index(op.f('ix_sys_user_groups_path'), table_name='sys_user_groups')
    op.drop_index(op.f('ix_sys_user_groups_parent_id'), table_name='sys_user_groups')
    op.drop_index(op.f('ix_sys_user_groups_owner_id'), table_name='sys_user_groups')
    op.drop_index(op.f('ix_sys_user_groups_name'), table_name='sys_user_groups')
    op.drop_index(op.f('ix_sys_user_groups_id'), table_name='sys_user_groups')
    op.drop_index('idx_group_tenant_name', table_name='sys_user_groups')
    op.drop_index('idx_group_parent_path', table_name='sys_user_groups')
    op.drop_table('sys_user_groups')
    op.drop_index(op.f('ix_sys_user_group_user_id'), table_name='sys_user_group')
    op.drop_index(op.f('ix_sys_user_group_tenant_id'), table_name='sys_user_group')
    op.drop_index(op.f('ix_sys_user_group_group_id'), table_name='sys_user_group')
    op.drop_index('idx_user_group_unique', table_name='sys_user_group')
    op.drop_index('idx_user_group_tenant', table_name='sys_user_group')
    op.drop_table('sys_user_group')
    op.drop_index(op.f('ix_sys_user_activities_user_id'), table_name='sys_user_activities')
    op.drop_index(op.f('ix_sys_user_activities_tenant_id'), table_name='sys_user_activities')
    op.drop_index(op.f('ix_sys_user_activities_id'), table_name='sys_user_activities')
    op.drop_index(op.f('ix_sys_user_activities_actor_id'), table_name='sys_user_activities')
    op.drop_index('idx_user_activity_tenant_time', table_name='sys_user_activities')
    op.drop_index('idx_user_activity_action', table_name='sys_user_activities')
    op.drop_table('sys_user_activities')
    op.drop_index(op.f('ix_sys_tenants_schema_name'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_owner_id'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_name'), table_name='sys_tenants')
    op.drop_index(op.f('ix_sys_tenants_id'), table_name='sys_tenants')
    op.drop_index('idx_tenant_status', table_name='sys_tenants')
    op.drop_index('idx_tenant_owner', table_name='sys_tenants')
    op.drop_table('sys_tenants')
    op.drop_index(op.f('ix_sys_tenant_users_user_id'), table_name='sys_tenant_users')
    op.drop_index(op.f('ix_sys_tenant_users_tenant_id'), table_name='sys_tenant_users')
    op.drop_index(op.f('ix_sys_tenant_users_id'), table_name='sys_tenant_users')
    op.drop_index('idx_tenant_user_unique', table_name='sys_tenant_users')
    op.drop_index('idx_tenant_role', table_name='sys_tenant_users')
    op.drop_table('sys_tenant_users')
    op.drop_index(op.f('ix_sys_tenant_databases_tenant_id'), table_name='sys_tenant_databases')
    op.drop_index(op.f('ix_sys_tenant_databases_id'), table_name='sys_tenant_databases')
    op.drop_index('idx_tenant_db_status', table_name='sys_tenant_databases')
    op.drop_table('sys_tenant_databases')
    op.drop_index(op.f('ix_sys_tenant_activities_user_id'), table_name='sys_tenant_activities')
    op.drop_index(op.f('ix_sys_tenant_activities_tenant_id'), table_name='sys_tenant_activities')
    op.drop_index(op.f('ix_sys_tenant_activities_id'), table_name='sys_tenant_activities')
    op.drop_index('idx_tenant_activity_user', table_name='sys_tenant_activities')
    op.drop_index('idx_tenant_activity_time', table_name='sys_tenant_activities')
    op.drop_index('idx_tenant_activity_action', table_name='sys_tenant_activities')
    op.drop_table('sys_tenant_activities')
    op.drop_index(op.f('ix_sys_teams_tenant_id'), table_name='sys_teams')
    op.drop_index(op.f('ix_sys_teams_path'), table_name='sys_teams')
    op.drop_index(op.f('ix_sys_teams_parent_id'), table_name='sys_teams')
    op.drop_index(op.f('ix_sys_teams_organization_id'), table_name='sys_teams')
    op.drop_index(op.f('ix_sys_teams_name'), table_name='sys_teams')
    op.drop_index(op.f('ix_sys_teams_id'), table_name='sys_teams')
    op.drop_index('idx_team_tenant', table_name='sys_teams')
    op.drop_index('idx_team_parent_path', table_name='sys_teams')
    op.drop_index('idx_team_org_name', table_name='sys_teams')
    op.drop_table('sys_teams')
    op.drop_index(op.f('ix_sys_roles_tenant_id'), table_name='sys_roles')
    op.drop_index(op.f('ix_sys_roles_name'), table_name='sys_roles')
    op.drop_index(op.f('ix_sys_roles_id'), table_name='sys_roles')
    op.drop_index('idx_role_type_level', table_name='sys_roles')
    op.drop_index('idx_role_tenant_name', table_name='sys_roles')
    op.drop_table('sys_roles')
    op.drop_index(op.f('ix_sys_role_permission_tenant_id'), table_name='sys_role_permission')
    op.drop_index(op.f('ix_sys_role_permission_role_id'), table_name='sys_role_permission')
    op.drop_index(op.f('ix_sys_role_permission_permission_id'), table_name='sys_role_permission')
    op.drop_index('idx_role_perm_unique', table_name='sys_role_permission')
    op.drop_index('idx_role_perm_tenant', table_name='sys_role_permission')
    op.drop_table('sys_role_permission')
    op.drop_index(op.f('ix_sys_permissions_resource_type'), table_name='sys_permissions')
    op.drop_index(op.f('ix_sys_permissions_name'), table_name='sys_permissions')
    op.drop_index(op.f('ix_sys_permissions_id'), table_name='sys_permissions')
    op.drop_index(op.f('ix_sys_permissions_category'), table_name='sys_permissions')
    op.drop_index(op.f('ix_sys_permissions_action'), table_name='sys_permissions')
    op.drop_index('idx_permission_resource_action', table_name='sys_permissions')
    op.drop_index('idx_permission_category_action', table_name='sys_permissions')
    op.drop_table('sys_permissions')
    op.drop_index(op.f('ix_sys_organizations_tenant_id'), table_name='sys_organizations')
    op.drop_index(op.f('ix_sys_organizations_path'), table_name='sys_organizations')
    op.drop_index(op.f('ix_sys_organizations_parent_id'), table_name='sys_organizations')
    op.drop_index(op.f('ix_sys_organizations_owner_id'), table_name='sys_organizations')
    op.drop_index(op.f('ix_sys_organizations_name'), table_name='sys_organizations')
    op.drop_index(op.f('ix_sys_organizations_id'), table_name='sys_organizations')
    op.drop_index('idx_org_tenant_name', table_name='sys_organizations')
    op.drop_index('idx_org_parent_path', table_name='sys_organizations')
    op.drop_index('idx_org_owner', table_name='sys_organizations')
    op.drop_table('sys_organizations')
    op.drop_index(op.f('ix_sys_org_activities_user_id'), table_name='sys_org_activities')
    op.drop_index(op.f('ix_sys_org_activities_tenant_id'), table_name='sys_org_activities')
    op.drop_index(op.f('ix_sys_org_activities_organization_id'), table_name='sys_org_activities')
    op.drop_index(op.f('ix_sys_org_activities_id'), table_name='sys_org_activities')
    op.drop_index('idx_org_activity_user', table_name='sys_org_activities')
    op.drop_index('idx_org_activity_time', table_name='sys_org_activities')
    op.drop_index('idx_org_activity_tenant', table_name='sys_org_activities')
    op.drop_index('idx_org_activity_action', table_name='sys_org_activities')
    op.drop_table('sys_org_activities')
    op.drop_index(op.f('ix_sys_login_history_user_id'), table_name='sys_login_history')
    op.drop_index(op.f('ix_sys_login_history_tenant_id'), table_name='sys_login_history')
    op.drop_index(op.f('ix_sys_login_history_session_id'), table_name='sys_login_history')
    op.drop_index(op.f('ix_sys_login_history_id'), table_name='sys_login_history')
    op.drop_index('idx_login_user_time', table_name='sys_login_history')
    op.drop_index('idx_login_tenant_time', table_name='sys_login_history')
    op.drop_index('idx_login_ip', table_name='sys_login_history')
    op.drop_table('sys_login_history')
    op.drop_index(op.f('ix_sys_invitations_token'), table_name='sys_invitations')
    op.drop_index(op.f('ix_sys_invitations_tenant_id'), table_name='sys_invitations')
    op.drop_index(op.f('ix_sys_invitations_team_id'), table_name='sys_invitations')
    op.drop_index(op.f('ix_sys_invitations_organization_id'), table_name='sys_invitations')
    op.drop_index(op.f('ix_sys_invitations_inviter_id'), table_name='sys_invitations')
    op.drop_index(op.f('ix_sys_invitations_invitee_id'), table_name='sys_invitations')
    op.drop_index(op.f('ix_sys_invitations_invitee_email'), table_name='sys_invitations')
    op.drop_index('idx_invitation_tenant_org', table_name='sys_invitations')
    op.drop_index('idx_invitation_expires', table_name='sys_invitations')
    op.drop_index('idx_invitation_email_status', table_name='sys_invitations')
    op.drop_table('sys_invitations')
    op.drop_index(op.f('ix_sys_group_role_tenant_id'), table_name='sys_group_role')
    op.drop_index(op.f('ix_sys_group_role_role_id'), table_name='sys_group_role')
    op.drop_index(op.f('ix_sys_group_role_group_id'), table_name='sys_group_role')
    op.drop_index('idx_group_role_unique', table_name='sys_group_role')
    op.drop_index('idx_group_role_tenant', table_name='sys_group_role')
    op.drop_table('sys_group_role')
    op.drop_index(op.f('ix_sys_group_permission_tenant_id'), table_name='sys_group_permission')
    op.drop_index(op.f('ix_sys_group_permission_permission_id'), table_name='sys_group_permission')
    op.drop_index(op.f('ix_sys_group_permission_group_id'), table_name='sys_group_permission')
    op.drop_index('idx_group_perm_unique', table_name='sys_group_permission')
    op.drop_index('idx_group_perm_tenant', table_name='sys_group_permission')
    op.drop_table('sys_group_permission')
    op.drop_index(op.f('ix_sys_folders_tenant_id'), table_name='sys_folders')
    op.drop_index(op.f('ix_sys_folders_path'), table_name='sys_folders')
    op.drop_index(op.f('ix_sys_folders_parent_id'), table_name='sys_folders')
    op.drop_index(op.f('ix_sys_folders_owner_id'), table_name='sys_folders')
    op.drop_index(op.f('ix_sys_folders_name'), table_name='sys_folders')
    op.drop_index(op.f('ix_sys_folders_id'), table_name='sys_folders')
    op.drop_index('idx_folder_tenant_owner', table_name='sys_folders')
    op.drop_index('idx_folder_path', table_name='sys_folders')
    op.drop_index('idx_folder_owner_parent', table_name='sys_folders')
    op.drop_table('sys_folders')
    op.drop_index(op.f('ix_sys_files_visibility'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_title'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_tenant_id'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_status'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_parent_folder_id'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_owner_id'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_original_name'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_id'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_file_type'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_file_hash'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_file_extension'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_created_at'), table_name='sys_files')
    op.drop_index(op.f('ix_sys_files_category'), table_name='sys_files')
    op.drop_index('idx_file_type_status', table_name='sys_files')
    op.drop_index('idx_file_tenant_owner', table_name='sys_files')
    op.drop_index('idx_file_tenant_category', table_name='sys_files')
    op.drop_index('idx_file_owner_status', table_name='sys_files')
    op.drop_index('idx_file_hash', table_name='sys_files')
    op.drop_index('idx_file_created', table_name='sys_files')
    op.drop_table('sys_files')
    op.drop_index(op.f('ix_sys_file_versions_tenant_id'), table_name='sys_file_versions')
    op.drop_index(op.f('ix_sys_file_versions_id'), table_name='sys_file_versions')
    op.drop_index(op.f('ix_sys_file_versions_file_id'), table_name='sys_file_versions')
    op.drop_index('idx_version_tenant', table_name='sys_file_versions')
    op.drop_index('idx_version_file_number', table_name='sys_file_versions')
    op.drop_table('sys_file_versions')
    op.drop_index(op.f('ix_sys_file_tags_owner_id'), table_name='sys_file_tags')
    op.drop_index(op.f('ix_sys_file_tags_name'), table_name='sys_file_tags')
    op.drop_index(op.f('ix_sys_file_tags_id'), table_name='sys_file_tags')
    op.drop_index('idx_tag_usage', table_name='sys_file_tags')
    op.drop_index('idx_tag_owner_name', table_name='sys_file_tags')
    op.drop_table('sys_file_tags')
    op.drop_index(op.f('ix_sys_file_tag_relations_tag_id'), table_name='sys_file_tag_relations')
    op.drop_index(op.f('ix_sys_file_tag_relations_id'), table_name='sys_file_tag_relations')
    op.drop_index(op.f('ix_sys_file_tag_relations_file_id'), table_name='sys_file_tag_relations')
    op.drop_index('idx_file_tag_unique', table_name='sys_file_tag_relations')
    op.drop_table('sys_file_tag_relations')
    op.drop_index(op.f('ix_sys_file_shares_id'), table_name='sys_file_shares')
    op.drop_index(op.f('ix_sys_file_shares_file_id'), table_name='sys_file_shares')
    op.drop_table('sys_file_shares')
    op.drop_index(op.f('ix_sys_file_comments_id'), table_name='sys_file_comments')
    op.drop_index(op.f('ix_sys_file_comments_file_id'), table_name='sys_file_comments')
    op.drop_table('sys_file_comments')
    op.drop_index(op.f('ix_sys_file_categories_path'), table_name='sys_file_categories')
    op.drop_index(op.f('ix_sys_file_categories_parent_id'), table_name='sys_file_categories')
    op.drop_index(op.f('ix_sys_file_categories_owner_id'), table_name='sys_file_categories')
    op.drop_index(op.f('ix_sys_file_categories_name'), table_name='sys_file_categories')
    op.drop_index(op.f('ix_sys_file_categories_id'), table_name='sys_file_categories')
    op.drop_index('idx_category_path', table_name='sys_file_categories')
    op.drop_index('idx_category_owner_name', table_name='sys_file_categories')
    op.drop_table('sys_file_categories')
    op.drop_index(op.f('ix_sys_file_activities_id'), table_name='sys_file_activities')
    op.drop_index(op.f('ix_sys_file_activities_file_id'), table_name='sys_file_activities')
    op.drop_index(op.f('ix_sys_file_activities_created_at'), table_name='sys_file_activities')
    op.drop_index(op.f('ix_sys_file_activities_action'), table_name='sys_file_activities')
    op.drop_index('idx_activity_user_time', table_name='sys_file_activities')
    op.drop_index('idx_activity_file_action', table_name='sys_file_activities')
    op.drop_table('sys_file_activities')
    op.drop_index(op.f('ix_sys_api_tokens_user_id'), table_name='sys_api_tokens')
    op.drop_index(op.f('ix_sys_api_tokens_token_key'), table_name='sys_api_tokens')
    op.drop_index(op.f('ix_sys_api_tokens_tenant_id'), table_name='sys_api_tokens')
    op.drop_index(op.f('ix_sys_api_tokens_id'), table_name='sys_api_tokens')
    op.drop_index('idx_token_user_tenant', table_name='sys_api_tokens')
    op.drop_index('idx_token_prefix', table_name='sys_api_tokens')
    op.drop_index('idx_token_active', table_name='sys_api_tokens')
    op.drop_table('sys_api_tokens')
    # ### end Alembic commands ###
