"""refresh DB Model

Revision ID: 36c50d2d33b3
Revises: 147df3af577f
Create Date: 2025-08-18 16:48:15.567914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36c50d2d33b3'
down_revision: Union[str, None] = '147df3af577f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 添加user_type字段，允许为空
    op.add_column('sys_users', sa.Column('user_type', sa.String(length=20), nullable=True, comment='用户类型：individual个人用户，enterprise企业用户，system系统用户'))
    
    # 2. 为现有用户设置默认值
    connection = op.get_bind()
    # 将超级管理员设置为system类型
    connection.execute(sa.text("""
        UPDATE sys_users 
        SET user_type = 'system' 
        WHERE is_superuser = true
    """))
    
    # 将其他用户设置为individual类型
    connection.execute(sa.text("""
        UPDATE sys_users 
        SET user_type = 'individual' 
        WHERE user_type IS NULL
    """))
    
    # 3. 设置字段为非空约束
    op.alter_column('sys_users', 'user_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_users', 'user_type')
    # ### end Alembic commands ###
