"""add_tenant_backup_models

Revision ID: 418a5b4a49f8
Revises: f1c5c1ecd7ef
Create Date: 2025-08-20 11:11:08.557362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '418a5b4a49f8'
down_revision: Union[str, None] = 'f1c5c1ecd7ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_tenant_backups',
    sa.Column('id', sa.String(length=50), nullable=False, comment='备份记录唯一标识ID'),
    sa.Column('source_tenant_id', sa.String(length=50), nullable=False, comment='源租户ID'),
    sa.Column('backup_tenant_id', sa.String(length=50), nullable=False, comment='备份租户ID'),
    sa.Column('backup_name', sa.String(length=255), nullable=False, comment='备份名称'),
    sa.Column('version', sa.Integer(), nullable=False, comment='备份版本号'),
    sa.Column('description', sa.Text(), nullable=True, comment='备份描述'),
    sa.Column('backup_type', sa.String(length=50), nullable=False, comment='备份类型（full/incremental）'),
    sa.Column('users_count', sa.Integer(), nullable=False, comment='备份的用户数量'),
    sa.Column('orgs_count', sa.Integer(), nullable=False, comment='备份的组织数量'),
    sa.Column('files_count', sa.Integer(), nullable=False, comment='备份的文件数量'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='备份状态（pending/in_progress/completed/failed）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='备份是否有效'),
    sa.Column('created_by', sa.String(length=50), nullable=False, comment='备份创建者用户ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='备份创建时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='备份完成时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='租户备份记录表，管理租户备份的版本和元数据'
    )
    op.create_index('idx_backup_created', 'sys_tenant_backups', ['created_at'], unique=False)
    op.create_index('idx_backup_source_tenant', 'sys_tenant_backups', ['source_tenant_id'], unique=False)
    op.create_index('idx_backup_version', 'sys_tenant_backups', ['source_tenant_id', 'version'], unique=False)
    op.create_index(op.f('ix_sys_tenant_backups_backup_tenant_id'), 'sys_tenant_backups', ['backup_tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_backups_id'), 'sys_tenant_backups', ['id'], unique=False)
    op.create_index(op.f('ix_sys_tenant_backups_source_tenant_id'), 'sys_tenant_backups', ['source_tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_tenant_backups_source_tenant_id'), table_name='sys_tenant_backups')
    op.drop_index(op.f('ix_sys_tenant_backups_id'), table_name='sys_tenant_backups')
    op.drop_index(op.f('ix_sys_tenant_backups_backup_tenant_id'), table_name='sys_tenant_backups')
    op.drop_index('idx_backup_version', table_name='sys_tenant_backups')
    op.drop_index('idx_backup_source_tenant', table_name='sys_tenant_backups')
    op.drop_index('idx_backup_created', table_name='sys_tenant_backups')
    op.drop_table('sys_tenant_backups')
    # ### end Alembic commands ###
