"""add user profile fields

Revision ID: 6db34e60509a
Revises: e90064748e55
Create Date: 2025-08-14 22:24:53.727968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6db34e60509a'
down_revision: Union[str, None] = 'e90064748e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_users', sa.Column('bio', sa.String(length=500), nullable=True, comment='用户个人简介'))
    op.add_column('sys_users', sa.Column('urls', sa.JSON(), nullable=True, comment='用户个人网站URL列表，JSON格式存储'))
    op.add_column('sys_users', sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True, comment='用户出生日期'))
    op.add_column('sys_users', sa.Column('preferred_language', sa.String(length=10), nullable=True, comment='用户首选语言'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sys_users', 'preferred_language')
    op.drop_column('sys_users', 'date_of_birth')
    op.drop_column('sys_users', 'urls')
    op.drop_column('sys_users', 'bio')
    # ### end Alembic commands ###
