"""add_password_policy_models

Revision ID: 9464ac24538e
Revises: ae49b1dd4c51
Create Date: 2025-08-19 11:08:44.442381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9464ac24538e'
down_revision: Union[str, None] = 'ae49b1dd4c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
