"""add priority field to organizations table

Revision ID: adea58a966d9
Revises: 418a5b4a49f8
Create Date: 2025-08-26 21:29:21.380087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adea58a966d9'
down_revision: Union[str, None] = '418a5b4a49f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the priority column with default value first
    op.add_column('sys_organizations', sa.Column('priority', sa.Integer(), nullable=True, comment='组织优先级，数值越大优先级越高'))
    
    # Update existing organizations to have default priority of 0
    op.execute("UPDATE sys_organizations SET priority = 0 WHERE priority IS NULL")
    
    # Make the column non-nullable
    op.alter_column('sys_organizations', 'priority', nullable=False)
    
    # Create the index
    op.create_index('idx_org_priority', 'sys_organizations', ['tenant_id', 'priority', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_org_priority', table_name='sys_organizations')
    op.drop_column('sys_organizations', 'priority')
    # ### end Alembic commands ###
