"""add oauth models for third party login

Revision ID: ae49b1dd4c51
Revises: 36c50d2d33b3
Create Date: 2025-08-18 20:10:12.517038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae49b1dd4c51'
down_revision: Union[str, None] = '36c50d2d33b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
