"""add_password_policy_system_models

Revision ID: f5bd3258a84a
Revises: 9464ac24538e
Create Date: 2025-08-19 11:10:02.538446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5bd3258a84a'
down_revision: Union[str, None] = '9464ac24538e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_oauth_accounts',
    sa.Column('id', sa.String(length=50), nullable=False, comment='绑定记录ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='OAuth提供商'),
    sa.Column('provider_account_id', sa.String(length=100), nullable=False, comment='第三方账号ID'),
    sa.Column('provider_account_email', sa.String(length=255), nullable=True, comment='第三方账号邮箱'),
    sa.Column('display_name', sa.String(length=100), nullable=True, comment='显示名称'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='头像地址'),
    sa.Column('profile_data', sa.JSON(), nullable=True, comment='第三方资料数据'),
    sa.Column('access_token', sa.Text(), nullable=True, comment='访问令牌（加密）'),
    sa.Column('refresh_token', sa.Text(), nullable=True, comment='刷新令牌（加密）'),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True, comment='令牌过期时间'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='是否为主绑定账号'),
    sa.Column('first_login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='首次登录时间'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='最后登录时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='第三方账号绑定表，存储用户与第三方OAuth账号的绑定关系'
    )
    op.create_index('idx_oauth_account_provider_email', 'sys_oauth_accounts', ['provider', 'provider_account_email'], unique=False)
    op.create_index('idx_oauth_account_provider_id', 'sys_oauth_accounts', ['provider', 'provider_account_id'], unique=True)
    op.create_index('idx_oauth_account_user', 'sys_oauth_accounts', ['user_id'], unique=False)
    op.create_index(op.f('ix_sys_oauth_accounts_id'), 'sys_oauth_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_sys_oauth_accounts_user_id'), 'sys_oauth_accounts', ['user_id'], unique=False)
    op.create_table('sys_oauth_login_logs',
    sa.Column('id', sa.String(length=50), nullable=False, comment='日志ID'),
    sa.Column('user_id', sa.String(length=50), nullable=True, comment='用户ID'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='OAuth提供商'),
    sa.Column('provider_account_id', sa.String(length=100), nullable=True, comment='第三方账号ID'),
    sa.Column('login_result', sa.String(length=20), nullable=False, comment='登录结果：success/failed/error'),
    sa.Column('error_code', sa.String(length=50), nullable=True, comment='错误码'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('client_ip', sa.String(length=45), nullable=True, comment='客户端IP'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理'),
    sa.Column('request_id', sa.String(length=50), nullable=True, comment='请求ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='OAuth登录日志表，记录第三方登录的详细日志信息'
    )
    op.create_index('idx_oauth_log_provider', 'sys_oauth_login_logs', ['provider'], unique=False)
    op.create_index('idx_oauth_log_time', 'sys_oauth_login_logs', ['created_at'], unique=False)
    op.create_index('idx_oauth_log_user', 'sys_oauth_login_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_sys_oauth_login_logs_id'), 'sys_oauth_login_logs', ['id'], unique=False)
    op.create_index(op.f('ix_sys_oauth_login_logs_user_id'), 'sys_oauth_login_logs', ['user_id'], unique=False)
    op.create_table('sys_oauth_provider_configs',
    sa.Column('id', sa.String(length=50), nullable=False, comment='配置ID'),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='OAuth提供商'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('client_id', sa.String(length=500), nullable=False, comment='OAuth客户端ID'),
    sa.Column('client_secret', sa.Text(), nullable=False, comment='OAuth客户端密钥'),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False, comment='回调地址'),
    sa.Column('scopes', sa.JSON(), nullable=True, comment='权限范围'),
    sa.Column('config_data', sa.JSON(), nullable=True, comment='扩展配置数据'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建者ID'),
    sa.PrimaryKeyConstraint('id'),
    comment='OAuth提供商配置表，存储各租户的OAuth应用配置信息'
    )
    op.create_index('idx_oauth_config_tenant_provider', 'sys_oauth_provider_configs', ['tenant_id', 'provider'], unique=True)
    op.create_index(op.f('ix_sys_oauth_provider_configs_id'), 'sys_oauth_provider_configs', ['id'], unique=False)
    op.create_index(op.f('ix_sys_oauth_provider_configs_tenant_id'), 'sys_oauth_provider_configs', ['tenant_id'], unique=False)
    op.create_table('sys_oauth_states',
    sa.Column('id', sa.String(length=50), nullable=False, comment='状态ID'),
    sa.Column('state_token', sa.String(length=255), nullable=False, comment='状态令牌'),
    sa.Column('provider', sa.String(length=20), nullable=False, comment='OAuth提供商'),
    sa.Column('redirect_url', sa.String(length=500), nullable=True, comment='登录成功后跳转地址'),
    sa.Column('client_ip', sa.String(length=45), nullable=True, comment='客户端IP'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='用户代理'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='过期时间'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='是否已使用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_token'),
    comment='OAuth状态管理表，用于防范CSRF攻击和状态跟踪'
    )
    op.create_index('idx_oauth_state_expires', 'sys_oauth_states', ['expires_at'], unique=False)
    op.create_index('idx_oauth_state_token', 'sys_oauth_states', ['state_token'], unique=False)
    op.create_index(op.f('ix_sys_oauth_states_id'), 'sys_oauth_states', ['id'], unique=False)
    op.create_table('sys_password_policies',
    sa.Column('id', sa.String(length=50), nullable=False, comment='策略唯一标识'),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='策略名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='策略描述'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='策略状态'),
    sa.Column('scope_type', sa.String(length=20), nullable=False, comment='策略作用域类型'),
    sa.Column('scope_id', sa.String(length=50), nullable=False, comment='作用域ID（组织、部门、团队等的ID）'),
    sa.Column('scope_name', sa.String(length=100), nullable=True, comment='作用域名称（冗余字段，便于查询）'),
    sa.Column('parent_policy_id', sa.String(length=50), nullable=True, comment='父级策略ID'),
    sa.Column('is_inherited', sa.Boolean(), nullable=True, comment='是否启用继承'),
    sa.Column('override_parent', sa.Boolean(), nullable=True, comment='是否覆盖父级策略'),
    sa.Column('rules', sa.JSON(), nullable=False, comment='密码策略规则'),
    sa.Column('created_by', sa.String(length=50), nullable=False, comment='创建者ID'),
    sa.Column('created_by_name', sa.String(length=100), nullable=True, comment='创建者姓名'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='最后修改者ID'),
    sa.Column('updated_by_name', sa.String(length=100), nullable=True, comment='最后修改者姓名'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='密码策略表，支持多层级组织的密码策略管理'
    )
    op.create_index('idx_password_policy_parent', 'sys_password_policies', ['parent_policy_id'], unique=False)
    op.create_index('idx_password_policy_status', 'sys_password_policies', ['status', 'deleted_at'], unique=False)
    op.create_index('idx_password_policy_tenant_scope', 'sys_password_policies', ['tenant_id', 'scope_type', 'scope_id'], unique=False)
    op.create_index(op.f('ix_sys_password_policies_id'), 'sys_password_policies', ['id'], unique=False)
    op.create_index(op.f('ix_sys_password_policies_parent_policy_id'), 'sys_password_policies', ['parent_policy_id'], unique=False)
    op.create_index(op.f('ix_sys_password_policies_tenant_id'), 'sys_password_policies', ['tenant_id'], unique=False)
    op.create_table('sys_password_policy_applications',
    sa.Column('id', sa.String(length=50), nullable=False, comment='应用记录唯一标识'),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('policy_id', sa.String(length=50), nullable=False, comment='策略ID'),
    sa.Column('policy_name', sa.String(length=100), nullable=False, comment='策略名称'),
    sa.Column('target_type', sa.String(length=20), nullable=False, comment='应用目标类型'),
    sa.Column('target_id', sa.String(length=50), nullable=False, comment='应用目标ID'),
    sa.Column('target_name', sa.String(length=100), nullable=True, comment='应用目标名称'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='应用状态'),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='应用时间'),
    sa.Column('applied_by', sa.String(length=50), nullable=False, comment='应用者ID'),
    sa.Column('applied_by_name', sa.String(length=100), nullable=True, comment='应用者姓名'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效开始时间'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='生效结束时间'),
    sa.Column('application_result', sa.JSON(), nullable=True, comment='应用结果详情'),
    sa.PrimaryKeyConstraint('id'),
    comment='密码策略应用记录表，记录策略的应用历史和状态'
    )
    op.create_index('idx_password_app_policy', 'sys_password_policy_applications', ['policy_id', 'status'], unique=False)
    op.create_index('idx_password_app_target', 'sys_password_policy_applications', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_password_app_tenant', 'sys_password_policy_applications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_password_policy_applications_id'), 'sys_password_policy_applications', ['id'], unique=False)
    op.create_index(op.f('ix_sys_password_policy_applications_policy_id'), 'sys_password_policy_applications', ['policy_id'], unique=False)
    op.create_index(op.f('ix_sys_password_policy_applications_tenant_id'), 'sys_password_policy_applications', ['tenant_id'], unique=False)
    op.create_table('sys_password_policy_rules',
    sa.Column('id', sa.String(length=50), nullable=False, comment='规则唯一标识'),
    sa.Column('policy_id', sa.String(length=50), nullable=False, comment='策略ID'),
    sa.Column('tenant_id', sa.String(length=50), nullable=False, comment='租户ID'),
    sa.Column('rule_type', sa.String(length=50), nullable=False, comment='规则类型'),
    sa.Column('rule_name', sa.String(length=100), nullable=False, comment='规则名称'),
    sa.Column('rule_value', sa.String(length=200), nullable=True, comment='规则值'),
    sa.Column('is_required', sa.Boolean(), nullable=True, comment='是否必须'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='验证失败时的错误消息'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='密码策略规则详情表，支持灵活的规则配置'
    )
    op.create_index('idx_password_rule_policy', 'sys_password_policy_rules', ['policy_id', 'is_active'], unique=False)
    op.create_index('idx_password_rule_tenant', 'sys_password_policy_rules', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sys_password_policy_rules_id'), 'sys_password_policy_rules', ['id'], unique=False)
    op.create_index(op.f('ix_sys_password_policy_rules_policy_id'), 'sys_password_policy_rules', ['policy_id'], unique=False)
    op.create_index(op.f('ix_sys_password_policy_rules_tenant_id'), 'sys_password_policy_rules', ['tenant_id'], unique=False)
    op.create_table('sys_password_policy_templates',
    sa.Column('id', sa.String(length=50), nullable=False, comment='模板唯一标识'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='模板描述'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='模板分类'),
    sa.Column('template_rules', sa.JSON(), nullable=False, comment='模板规则配置'),
    sa.Column('is_system', sa.Boolean(), nullable=True, comment='是否系统内置模板'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开模板'),
    sa.Column('usage_count', sa.Integer(), nullable=True, comment='使用次数'),
    sa.Column('applicable_scopes', sa.JSON(), nullable=True, comment='适用的作用域类型'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建者ID'),
    sa.Column('created_by_name', sa.String(length=100), nullable=True, comment='创建者姓名'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='密码策略模板表，提供预定义的策略模板'
    )
    op.create_index('idx_password_template_category', 'sys_password_policy_templates', ['category', 'is_public'], unique=False)
    op.create_index('idx_password_template_system', 'sys_password_policy_templates', ['is_system'], unique=False)
    op.create_index(op.f('ix_sys_password_policy_templates_id'), 'sys_password_policy_templates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_password_policy_templates_id'), table_name='sys_password_policy_templates')
    op.drop_index('idx_password_template_system', table_name='sys_password_policy_templates')
    op.drop_index('idx_password_template_category', table_name='sys_password_policy_templates')
    op.drop_table('sys_password_policy_templates')
    op.drop_index(op.f('ix_sys_password_policy_rules_tenant_id'), table_name='sys_password_policy_rules')
    op.drop_index(op.f('ix_sys_password_policy_rules_policy_id'), table_name='sys_password_policy_rules')
    op.drop_index(op.f('ix_sys_password_policy_rules_id'), table_name='sys_password_policy_rules')
    op.drop_index('idx_password_rule_tenant', table_name='sys_password_policy_rules')
    op.drop_index('idx_password_rule_policy', table_name='sys_password_policy_rules')
    op.drop_table('sys_password_policy_rules')
    op.drop_index(op.f('ix_sys_password_policy_applications_tenant_id'), table_name='sys_password_policy_applications')
    op.drop_index(op.f('ix_sys_password_policy_applications_policy_id'), table_name='sys_password_policy_applications')
    op.drop_index(op.f('ix_sys_password_policy_applications_id'), table_name='sys_password_policy_applications')
    op.drop_index('idx_password_app_tenant', table_name='sys_password_policy_applications')
    op.drop_index('idx_password_app_target', table_name='sys_password_policy_applications')
    op.drop_index('idx_password_app_policy', table_name='sys_password_policy_applications')
    op.drop_table('sys_password_policy_applications')
    op.drop_index(op.f('ix_sys_password_policies_tenant_id'), table_name='sys_password_policies')
    op.drop_index(op.f('ix_sys_password_policies_parent_policy_id'), table_name='sys_password_policies')
    op.drop_index(op.f('ix_sys_password_policies_id'), table_name='sys_password_policies')
    op.drop_index('idx_password_policy_tenant_scope', table_name='sys_password_policies')
    op.drop_index('idx_password_policy_status', table_name='sys_password_policies')
    op.drop_index('idx_password_policy_parent', table_name='sys_password_policies')
    op.drop_table('sys_password_policies')
    op.drop_index(op.f('ix_sys_oauth_states_id'), table_name='sys_oauth_states')
    op.drop_index('idx_oauth_state_token', table_name='sys_oauth_states')
    op.drop_index('idx_oauth_state_expires', table_name='sys_oauth_states')
    op.drop_table('sys_oauth_states')
    op.drop_index(op.f('ix_sys_oauth_provider_configs_tenant_id'), table_name='sys_oauth_provider_configs')
    op.drop_index(op.f('ix_sys_oauth_provider_configs_id'), table_name='sys_oauth_provider_configs')
    op.drop_index('idx_oauth_config_tenant_provider', table_name='sys_oauth_provider_configs')
    op.drop_table('sys_oauth_provider_configs')
    op.drop_index(op.f('ix_sys_oauth_login_logs_user_id'), table_name='sys_oauth_login_logs')
    op.drop_index(op.f('ix_sys_oauth_login_logs_id'), table_name='sys_oauth_login_logs')
    op.drop_index('idx_oauth_log_user', table_name='sys_oauth_login_logs')
    op.drop_index('idx_oauth_log_time', table_name='sys_oauth_login_logs')
    op.drop_index('idx_oauth_log_provider', table_name='sys_oauth_login_logs')
    op.drop_table('sys_oauth_login_logs')
    op.drop_index(op.f('ix_sys_oauth_accounts_user_id'), table_name='sys_oauth_accounts')
    op.drop_index(op.f('ix_sys_oauth_accounts_id'), table_name='sys_oauth_accounts')
    op.drop_index('idx_oauth_account_user', table_name='sys_oauth_accounts')
    op.drop_index('idx_oauth_account_provider_id', table_name='sys_oauth_accounts')
    op.drop_index('idx_oauth_account_provider_email', table_name='sys_oauth_accounts')
    op.drop_table('sys_oauth_accounts')
    # ### end Alembic commands ###
