/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedManagementIndexRouteImport } from './routes/_authenticated/management/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAiChatsIndexRouteImport } from './routes/_authenticated/ai-chats/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsMcpRouteImport } from './routes/_authenticated/settings/mcp'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedManagementUsersRouteImport } from './routes/_authenticated/management/users'
import { Route as AuthenticatedManagementAiModelsRouteImport } from './routes/_authenticated/management/ai-models'
import { Route as AuthenticatedKnowledgeWechatRouteImport } from './routes/_authenticated/knowledge/wechat'
import { Route as AuthenticatedKnowledgeWebBlogsRouteImport } from './routes/_authenticated/knowledge/web-blogs'
import { Route as AuthenticatedKnowledgeOrganizationsRouteImport } from './routes/_authenticated/knowledge/organizations'
import { Route as AuthenticatedKnowledgeGraphRouteImport } from './routes/_authenticated/knowledge/graph'
import { Route as AuthenticatedKnowledgeDepartmentsRouteImport } from './routes/_authenticated/knowledge/departments'
import { Route as AuthenticatedDocumentsTrashRouteImport } from './routes/_authenticated/documents/trash'
import { Route as AuthenticatedDocumentsStorageRouteImport } from './routes/_authenticated/documents/storage'
import { Route as AuthenticatedDocumentsSharedRouteImport } from './routes/_authenticated/documents/shared'
import { Route as AuthenticatedDocumentsRecentRouteImport } from './routes/_authenticated/documents/recent'
import { Route as AuthenticatedDocumentsFavoritesRouteImport } from './routes/_authenticated/documents/favorites'
import { Route as AuthenticatedManagementSystemUsersRouteImport } from './routes/_authenticated/management/system/users'
import { Route as AuthenticatedManagementSystemTenantsRouteImport } from './routes/_authenticated/management/system/tenants'
import { Route as AuthenticatedManagementSystemIntegrationsRouteImport } from './routes/_authenticated/management/system/integrations'
import { Route as AuthenticatedManagementSystemConfigRouteImport } from './routes/_authenticated/management/system/config'
import { Route as AuthenticatedManagementSystemAiModelsRouteImport } from './routes/_authenticated/management/system/ai-models'
import { Route as AuthenticatedManagementSecurityRolesRouteImport } from './routes/_authenticated/management/security/roles'
import { Route as AuthenticatedManagementSecurityPasswordPoliciesRouteImport } from './routes/_authenticated/management/security/password-policies'
import { Route as AuthenticatedManagementSecurityAuditRouteImport } from './routes/_authenticated/management/security/audit'
import { Route as AuthenticatedManagementSecurityAccessRouteImport } from './routes/_authenticated/management/security/access'
import { Route as AuthenticatedManagementOrganizationUsersRouteImport } from './routes/_authenticated/management/organization/users'
import { Route as AuthenticatedManagementOrganizationHierarchyRouteImport } from './routes/_authenticated/management/organization/hierarchy'
import { Route as AuthenticatedManagementOrganizationChartRouteImport } from './routes/_authenticated/management/organization/chart'
import { Route as AuthenticatedDocumentsSettingsKnowledgeQualityAssessmentRouteImport } from './routes/_authenticated/documents/settings/knowledgeQualityAssessment'
import { Route as AuthenticatedDocumentsSettingsCategoriesRouteImport } from './routes/_authenticated/documents/settings/categories'
import { Route as AuthenticatedAuthOauthCallbackProviderRouteImport } from './routes/_authenticated/auth/oauth/callback/$provider'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedManagementIndexRoute =
  AuthenticatedManagementIndexRouteImport.update({
    id: '/management/',
    path: '/management/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiChatsIndexRoute =
  AuthenticatedAiChatsIndexRouteImport.update({
    id: '/ai-chats/',
    path: '/ai-chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsMcpRoute =
  AuthenticatedSettingsMcpRouteImport.update({
    id: '/mcp',
    path: '/mcp',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedManagementUsersRoute =
  AuthenticatedManagementUsersRouteImport.update({
    id: '/management/users',
    path: '/management/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagementAiModelsRoute =
  AuthenticatedManagementAiModelsRouteImport.update({
    id: '/management/ai-models',
    path: '/management/ai-models',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeWechatRoute =
  AuthenticatedKnowledgeWechatRouteImport.update({
    id: '/knowledge/wechat',
    path: '/knowledge/wechat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeWebBlogsRoute =
  AuthenticatedKnowledgeWebBlogsRouteImport.update({
    id: '/knowledge/web-blogs',
    path: '/knowledge/web-blogs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeOrganizationsRoute =
  AuthenticatedKnowledgeOrganizationsRouteImport.update({
    id: '/knowledge/organizations',
    path: '/knowledge/organizations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeGraphRoute =
  AuthenticatedKnowledgeGraphRouteImport.update({
    id: '/knowledge/graph',
    path: '/knowledge/graph',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeDepartmentsRoute =
  AuthenticatedKnowledgeDepartmentsRouteImport.update({
    id: '/knowledge/departments',
    path: '/knowledge/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsTrashRoute =
  AuthenticatedDocumentsTrashRouteImport.update({
    id: '/documents/trash',
    path: '/documents/trash',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsStorageRoute =
  AuthenticatedDocumentsStorageRouteImport.update({
    id: '/documents/storage',
    path: '/documents/storage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsSharedRoute =
  AuthenticatedDocumentsSharedRouteImport.update({
    id: '/documents/shared',
    path: '/documents/shared',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRecentRoute =
  AuthenticatedDocumentsRecentRouteImport.update({
    id: '/documents/recent',
    path: '/documents/recent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsFavoritesRoute =
  AuthenticatedDocumentsFavoritesRouteImport.update({
    id: '/documents/favorites',
    path: '/documents/favorites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagementSystemUsersRoute =
  AuthenticatedManagementSystemUsersRouteImport.update({
    id: '/management/system/users',
    path: '/management/system/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagementSystemTenantsRoute =
  AuthenticatedManagementSystemTenantsRouteImport.update({
    id: '/management/system/tenants',
    path: '/management/system/tenants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagementSystemIntegrationsRoute =
  AuthenticatedManagementSystemIntegrationsRouteImport.update({
    id: '/management/system/integrations',
    path: '/management/system/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagementSystemConfigRoute =
  AuthenticatedManagementSystemConfigRouteImport.update({
    id: '/management/system/config',
    path: '/management/system/config',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagementSystemAiModelsRoute =
  AuthenticatedManagementSystemAiModelsRouteImport.update({
    id: '/management/system/ai-models',
    path: '/management/system/ai-models',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagementSecurityRolesRoute =
  AuthenticatedManagementSecurityRolesRouteImport.update({
    id: '/management/security/roles',
    path: '/management/security/roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagementSecurityPasswordPoliciesRoute =
  AuthenticatedManagementSecurityPasswordPoliciesRouteImport.update({
    id: '/management/security/password-policies',
    path: '/management/security/password-policies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagementSecurityAuditRoute =
  AuthenticatedManagementSecurityAuditRouteImport.update({
    id: '/management/security/audit',
    path: '/management/security/audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagementSecurityAccessRoute =
  AuthenticatedManagementSecurityAccessRouteImport.update({
    id: '/management/security/access',
    path: '/management/security/access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagementOrganizationUsersRoute =
  AuthenticatedManagementOrganizationUsersRouteImport.update({
    id: '/management/organization/users',
    path: '/management/organization/users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagementOrganizationHierarchyRoute =
  AuthenticatedManagementOrganizationHierarchyRouteImport.update({
    id: '/management/organization/hierarchy',
    path: '/management/organization/hierarchy',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagementOrganizationChartRoute =
  AuthenticatedManagementOrganizationChartRouteImport.update({
    id: '/management/organization/chart',
    path: '/management/organization/chart',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsSettingsKnowledgeQualityAssessmentRoute =
  AuthenticatedDocumentsSettingsKnowledgeQualityAssessmentRouteImport.update({
    id: '/documents/settings/knowledgeQualityAssessment',
    path: '/documents/settings/knowledgeQualityAssessment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsSettingsCategoriesRoute =
  AuthenticatedDocumentsSettingsCategoriesRouteImport.update({
    id: '/documents/settings/categories',
    path: '/documents/settings/categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuthOauthCallbackProviderRoute =
  AuthenticatedAuthOauthCallbackProviderRouteImport.update({
    id: '/auth/oauth/callback/$provider',
    path: '/auth/oauth/callback/$provider',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/documents/favorites': typeof AuthenticatedDocumentsFavoritesRoute
  '/documents/recent': typeof AuthenticatedDocumentsRecentRoute
  '/documents/shared': typeof AuthenticatedDocumentsSharedRoute
  '/documents/storage': typeof AuthenticatedDocumentsStorageRoute
  '/documents/trash': typeof AuthenticatedDocumentsTrashRoute
  '/knowledge/departments': typeof AuthenticatedKnowledgeDepartmentsRoute
  '/knowledge/graph': typeof AuthenticatedKnowledgeGraphRoute
  '/knowledge/organizations': typeof AuthenticatedKnowledgeOrganizationsRoute
  '/knowledge/web-blogs': typeof AuthenticatedKnowledgeWebBlogsRoute
  '/knowledge/wechat': typeof AuthenticatedKnowledgeWechatRoute
  '/management/ai-models': typeof AuthenticatedManagementAiModelsRoute
  '/management/users': typeof AuthenticatedManagementUsersRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/mcp': typeof AuthenticatedSettingsMcpRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/ai-chats': typeof AuthenticatedAiChatsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/management': typeof AuthenticatedManagementIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/documents/settings/categories': typeof AuthenticatedDocumentsSettingsCategoriesRoute
  '/documents/settings/knowledgeQualityAssessment': typeof AuthenticatedDocumentsSettingsKnowledgeQualityAssessmentRoute
  '/management/organization/chart': typeof AuthenticatedManagementOrganizationChartRoute
  '/management/organization/hierarchy': typeof AuthenticatedManagementOrganizationHierarchyRoute
  '/management/organization/users': typeof AuthenticatedManagementOrganizationUsersRoute
  '/management/security/access': typeof AuthenticatedManagementSecurityAccessRoute
  '/management/security/audit': typeof AuthenticatedManagementSecurityAuditRoute
  '/management/security/password-policies': typeof AuthenticatedManagementSecurityPasswordPoliciesRoute
  '/management/security/roles': typeof AuthenticatedManagementSecurityRolesRoute
  '/management/system/ai-models': typeof AuthenticatedManagementSystemAiModelsRoute
  '/management/system/config': typeof AuthenticatedManagementSystemConfigRoute
  '/management/system/integrations': typeof AuthenticatedManagementSystemIntegrationsRoute
  '/management/system/tenants': typeof AuthenticatedManagementSystemTenantsRoute
  '/management/system/users': typeof AuthenticatedManagementSystemUsersRoute
  '/auth/oauth/callback/$provider': typeof AuthenticatedAuthOauthCallbackProviderRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/documents/favorites': typeof AuthenticatedDocumentsFavoritesRoute
  '/documents/recent': typeof AuthenticatedDocumentsRecentRoute
  '/documents/shared': typeof AuthenticatedDocumentsSharedRoute
  '/documents/storage': typeof AuthenticatedDocumentsStorageRoute
  '/documents/trash': typeof AuthenticatedDocumentsTrashRoute
  '/knowledge/departments': typeof AuthenticatedKnowledgeDepartmentsRoute
  '/knowledge/graph': typeof AuthenticatedKnowledgeGraphRoute
  '/knowledge/organizations': typeof AuthenticatedKnowledgeOrganizationsRoute
  '/knowledge/web-blogs': typeof AuthenticatedKnowledgeWebBlogsRoute
  '/knowledge/wechat': typeof AuthenticatedKnowledgeWechatRoute
  '/management/ai-models': typeof AuthenticatedManagementAiModelsRoute
  '/management/users': typeof AuthenticatedManagementUsersRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/mcp': typeof AuthenticatedSettingsMcpRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/ai-chats': typeof AuthenticatedAiChatsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/management': typeof AuthenticatedManagementIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/documents/settings/categories': typeof AuthenticatedDocumentsSettingsCategoriesRoute
  '/documents/settings/knowledgeQualityAssessment': typeof AuthenticatedDocumentsSettingsKnowledgeQualityAssessmentRoute
  '/management/organization/chart': typeof AuthenticatedManagementOrganizationChartRoute
  '/management/organization/hierarchy': typeof AuthenticatedManagementOrganizationHierarchyRoute
  '/management/organization/users': typeof AuthenticatedManagementOrganizationUsersRoute
  '/management/security/access': typeof AuthenticatedManagementSecurityAccessRoute
  '/management/security/audit': typeof AuthenticatedManagementSecurityAuditRoute
  '/management/security/password-policies': typeof AuthenticatedManagementSecurityPasswordPoliciesRoute
  '/management/security/roles': typeof AuthenticatedManagementSecurityRolesRoute
  '/management/system/ai-models': typeof AuthenticatedManagementSystemAiModelsRoute
  '/management/system/config': typeof AuthenticatedManagementSystemConfigRoute
  '/management/system/integrations': typeof AuthenticatedManagementSystemIntegrationsRoute
  '/management/system/tenants': typeof AuthenticatedManagementSystemTenantsRoute
  '/management/system/users': typeof AuthenticatedManagementSystemUsersRoute
  '/auth/oauth/callback/$provider': typeof AuthenticatedAuthOauthCallbackProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/documents/favorites': typeof AuthenticatedDocumentsFavoritesRoute
  '/_authenticated/documents/recent': typeof AuthenticatedDocumentsRecentRoute
  '/_authenticated/documents/shared': typeof AuthenticatedDocumentsSharedRoute
  '/_authenticated/documents/storage': typeof AuthenticatedDocumentsStorageRoute
  '/_authenticated/documents/trash': typeof AuthenticatedDocumentsTrashRoute
  '/_authenticated/knowledge/departments': typeof AuthenticatedKnowledgeDepartmentsRoute
  '/_authenticated/knowledge/graph': typeof AuthenticatedKnowledgeGraphRoute
  '/_authenticated/knowledge/organizations': typeof AuthenticatedKnowledgeOrganizationsRoute
  '/_authenticated/knowledge/web-blogs': typeof AuthenticatedKnowledgeWebBlogsRoute
  '/_authenticated/knowledge/wechat': typeof AuthenticatedKnowledgeWechatRoute
  '/_authenticated/management/ai-models': typeof AuthenticatedManagementAiModelsRoute
  '/_authenticated/management/users': typeof AuthenticatedManagementUsersRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/mcp': typeof AuthenticatedSettingsMcpRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/ai-chats/': typeof AuthenticatedAiChatsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/management/': typeof AuthenticatedManagementIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/documents/settings/categories': typeof AuthenticatedDocumentsSettingsCategoriesRoute
  '/_authenticated/documents/settings/knowledgeQualityAssessment': typeof AuthenticatedDocumentsSettingsKnowledgeQualityAssessmentRoute
  '/_authenticated/management/organization/chart': typeof AuthenticatedManagementOrganizationChartRoute
  '/_authenticated/management/organization/hierarchy': typeof AuthenticatedManagementOrganizationHierarchyRoute
  '/_authenticated/management/organization/users': typeof AuthenticatedManagementOrganizationUsersRoute
  '/_authenticated/management/security/access': typeof AuthenticatedManagementSecurityAccessRoute
  '/_authenticated/management/security/audit': typeof AuthenticatedManagementSecurityAuditRoute
  '/_authenticated/management/security/password-policies': typeof AuthenticatedManagementSecurityPasswordPoliciesRoute
  '/_authenticated/management/security/roles': typeof AuthenticatedManagementSecurityRolesRoute
  '/_authenticated/management/system/ai-models': typeof AuthenticatedManagementSystemAiModelsRoute
  '/_authenticated/management/system/config': typeof AuthenticatedManagementSystemConfigRoute
  '/_authenticated/management/system/integrations': typeof AuthenticatedManagementSystemIntegrationsRoute
  '/_authenticated/management/system/tenants': typeof AuthenticatedManagementSystemTenantsRoute
  '/_authenticated/management/system/users': typeof AuthenticatedManagementSystemUsersRoute
  '/_authenticated/auth/oauth/callback/$provider': typeof AuthenticatedAuthOauthCallbackProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/documents/favorites'
    | '/documents/recent'
    | '/documents/shared'
    | '/documents/storage'
    | '/documents/trash'
    | '/knowledge/departments'
    | '/knowledge/graph'
    | '/knowledge/organizations'
    | '/knowledge/web-blogs'
    | '/knowledge/wechat'
    | '/management/ai-models'
    | '/management/users'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/mcp'
    | '/settings/notifications'
    | '/ai-chats'
    | '/apps'
    | '/chats'
    | '/documents'
    | '/help-center'
    | '/management'
    | '/settings/'
    | '/tasks'
    | '/documents/settings/categories'
    | '/documents/settings/knowledgeQualityAssessment'
    | '/management/organization/chart'
    | '/management/organization/hierarchy'
    | '/management/organization/users'
    | '/management/security/access'
    | '/management/security/audit'
    | '/management/security/password-policies'
    | '/management/security/roles'
    | '/management/system/ai-models'
    | '/management/system/config'
    | '/management/system/integrations'
    | '/management/system/tenants'
    | '/management/system/users'
    | '/auth/oauth/callback/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/documents/favorites'
    | '/documents/recent'
    | '/documents/shared'
    | '/documents/storage'
    | '/documents/trash'
    | '/knowledge/departments'
    | '/knowledge/graph'
    | '/knowledge/organizations'
    | '/knowledge/web-blogs'
    | '/knowledge/wechat'
    | '/management/ai-models'
    | '/management/users'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/mcp'
    | '/settings/notifications'
    | '/ai-chats'
    | '/apps'
    | '/chats'
    | '/documents'
    | '/help-center'
    | '/management'
    | '/settings'
    | '/tasks'
    | '/documents/settings/categories'
    | '/documents/settings/knowledgeQualityAssessment'
    | '/management/organization/chart'
    | '/management/organization/hierarchy'
    | '/management/organization/users'
    | '/management/security/access'
    | '/management/security/audit'
    | '/management/security/password-policies'
    | '/management/security/roles'
    | '/management/system/ai-models'
    | '/management/system/config'
    | '/management/system/integrations'
    | '/management/system/tenants'
    | '/management/system/users'
    | '/auth/oauth/callback/$provider'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/documents/favorites'
    | '/_authenticated/documents/recent'
    | '/_authenticated/documents/shared'
    | '/_authenticated/documents/storage'
    | '/_authenticated/documents/trash'
    | '/_authenticated/knowledge/departments'
    | '/_authenticated/knowledge/graph'
    | '/_authenticated/knowledge/organizations'
    | '/_authenticated/knowledge/web-blogs'
    | '/_authenticated/knowledge/wechat'
    | '/_authenticated/management/ai-models'
    | '/_authenticated/management/users'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/mcp'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/ai-chats/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/documents/'
    | '/_authenticated/help-center/'
    | '/_authenticated/management/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/documents/settings/categories'
    | '/_authenticated/documents/settings/knowledgeQualityAssessment'
    | '/_authenticated/management/organization/chart'
    | '/_authenticated/management/organization/hierarchy'
    | '/_authenticated/management/organization/users'
    | '/_authenticated/management/security/access'
    | '/_authenticated/management/security/audit'
    | '/_authenticated/management/security/password-policies'
    | '/_authenticated/management/security/roles'
    | '/_authenticated/management/system/ai-models'
    | '/_authenticated/management/system/config'
    | '/_authenticated/management/system/integrations'
    | '/_authenticated/management/system/tenants'
    | '/_authenticated/management/system/users'
    | '/_authenticated/auth/oauth/callback/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/management/': {
      id: '/_authenticated/management/'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof AuthenticatedManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-chats/': {
      id: '/_authenticated/ai-chats/'
      path: '/ai-chats'
      fullPath: '/ai-chats'
      preLoaderRoute: typeof AuthenticatedAiChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/mcp': {
      id: '/_authenticated/settings/mcp'
      path: '/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof AuthenticatedSettingsMcpRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/management/users': {
      id: '/_authenticated/management/users'
      path: '/management/users'
      fullPath: '/management/users'
      preLoaderRoute: typeof AuthenticatedManagementUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management/ai-models': {
      id: '/_authenticated/management/ai-models'
      path: '/management/ai-models'
      fullPath: '/management/ai-models'
      preLoaderRoute: typeof AuthenticatedManagementAiModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/wechat': {
      id: '/_authenticated/knowledge/wechat'
      path: '/knowledge/wechat'
      fullPath: '/knowledge/wechat'
      preLoaderRoute: typeof AuthenticatedKnowledgeWechatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/web-blogs': {
      id: '/_authenticated/knowledge/web-blogs'
      path: '/knowledge/web-blogs'
      fullPath: '/knowledge/web-blogs'
      preLoaderRoute: typeof AuthenticatedKnowledgeWebBlogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/organizations': {
      id: '/_authenticated/knowledge/organizations'
      path: '/knowledge/organizations'
      fullPath: '/knowledge/organizations'
      preLoaderRoute: typeof AuthenticatedKnowledgeOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/graph': {
      id: '/_authenticated/knowledge/graph'
      path: '/knowledge/graph'
      fullPath: '/knowledge/graph'
      preLoaderRoute: typeof AuthenticatedKnowledgeGraphRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge/departments': {
      id: '/_authenticated/knowledge/departments'
      path: '/knowledge/departments'
      fullPath: '/knowledge/departments'
      preLoaderRoute: typeof AuthenticatedKnowledgeDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/trash': {
      id: '/_authenticated/documents/trash'
      path: '/documents/trash'
      fullPath: '/documents/trash'
      preLoaderRoute: typeof AuthenticatedDocumentsTrashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/storage': {
      id: '/_authenticated/documents/storage'
      path: '/documents/storage'
      fullPath: '/documents/storage'
      preLoaderRoute: typeof AuthenticatedDocumentsStorageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/shared': {
      id: '/_authenticated/documents/shared'
      path: '/documents/shared'
      fullPath: '/documents/shared'
      preLoaderRoute: typeof AuthenticatedDocumentsSharedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/recent': {
      id: '/_authenticated/documents/recent'
      path: '/documents/recent'
      fullPath: '/documents/recent'
      preLoaderRoute: typeof AuthenticatedDocumentsRecentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/favorites': {
      id: '/_authenticated/documents/favorites'
      path: '/documents/favorites'
      fullPath: '/documents/favorites'
      preLoaderRoute: typeof AuthenticatedDocumentsFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management/system/users': {
      id: '/_authenticated/management/system/users'
      path: '/management/system/users'
      fullPath: '/management/system/users'
      preLoaderRoute: typeof AuthenticatedManagementSystemUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management/system/tenants': {
      id: '/_authenticated/management/system/tenants'
      path: '/management/system/tenants'
      fullPath: '/management/system/tenants'
      preLoaderRoute: typeof AuthenticatedManagementSystemTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management/system/integrations': {
      id: '/_authenticated/management/system/integrations'
      path: '/management/system/integrations'
      fullPath: '/management/system/integrations'
      preLoaderRoute: typeof AuthenticatedManagementSystemIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management/system/config': {
      id: '/_authenticated/management/system/config'
      path: '/management/system/config'
      fullPath: '/management/system/config'
      preLoaderRoute: typeof AuthenticatedManagementSystemConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management/system/ai-models': {
      id: '/_authenticated/management/system/ai-models'
      path: '/management/system/ai-models'
      fullPath: '/management/system/ai-models'
      preLoaderRoute: typeof AuthenticatedManagementSystemAiModelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management/security/roles': {
      id: '/_authenticated/management/security/roles'
      path: '/management/security/roles'
      fullPath: '/management/security/roles'
      preLoaderRoute: typeof AuthenticatedManagementSecurityRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management/security/password-policies': {
      id: '/_authenticated/management/security/password-policies'
      path: '/management/security/password-policies'
      fullPath: '/management/security/password-policies'
      preLoaderRoute: typeof AuthenticatedManagementSecurityPasswordPoliciesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management/security/audit': {
      id: '/_authenticated/management/security/audit'
      path: '/management/security/audit'
      fullPath: '/management/security/audit'
      preLoaderRoute: typeof AuthenticatedManagementSecurityAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management/security/access': {
      id: '/_authenticated/management/security/access'
      path: '/management/security/access'
      fullPath: '/management/security/access'
      preLoaderRoute: typeof AuthenticatedManagementSecurityAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management/organization/users': {
      id: '/_authenticated/management/organization/users'
      path: '/management/organization/users'
      fullPath: '/management/organization/users'
      preLoaderRoute: typeof AuthenticatedManagementOrganizationUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management/organization/hierarchy': {
      id: '/_authenticated/management/organization/hierarchy'
      path: '/management/organization/hierarchy'
      fullPath: '/management/organization/hierarchy'
      preLoaderRoute: typeof AuthenticatedManagementOrganizationHierarchyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/management/organization/chart': {
      id: '/_authenticated/management/organization/chart'
      path: '/management/organization/chart'
      fullPath: '/management/organization/chart'
      preLoaderRoute: typeof AuthenticatedManagementOrganizationChartRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/settings/knowledgeQualityAssessment': {
      id: '/_authenticated/documents/settings/knowledgeQualityAssessment'
      path: '/documents/settings/knowledgeQualityAssessment'
      fullPath: '/documents/settings/knowledgeQualityAssessment'
      preLoaderRoute: typeof AuthenticatedDocumentsSettingsKnowledgeQualityAssessmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents/settings/categories': {
      id: '/_authenticated/documents/settings/categories'
      path: '/documents/settings/categories'
      fullPath: '/documents/settings/categories'
      preLoaderRoute: typeof AuthenticatedDocumentsSettingsCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/auth/oauth/callback/$provider': {
      id: '/_authenticated/auth/oauth/callback/$provider'
      path: '/auth/oauth/callback/$provider'
      fullPath: '/auth/oauth/callback/$provider'
      preLoaderRoute: typeof AuthenticatedAuthOauthCallbackProviderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsMcpRoute: typeof AuthenticatedSettingsMcpRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsMcpRoute: AuthenticatedSettingsMcpRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDocumentsFavoritesRoute: typeof AuthenticatedDocumentsFavoritesRoute
  AuthenticatedDocumentsRecentRoute: typeof AuthenticatedDocumentsRecentRoute
  AuthenticatedDocumentsSharedRoute: typeof AuthenticatedDocumentsSharedRoute
  AuthenticatedDocumentsStorageRoute: typeof AuthenticatedDocumentsStorageRoute
  AuthenticatedDocumentsTrashRoute: typeof AuthenticatedDocumentsTrashRoute
  AuthenticatedKnowledgeDepartmentsRoute: typeof AuthenticatedKnowledgeDepartmentsRoute
  AuthenticatedKnowledgeGraphRoute: typeof AuthenticatedKnowledgeGraphRoute
  AuthenticatedKnowledgeOrganizationsRoute: typeof AuthenticatedKnowledgeOrganizationsRoute
  AuthenticatedKnowledgeWebBlogsRoute: typeof AuthenticatedKnowledgeWebBlogsRoute
  AuthenticatedKnowledgeWechatRoute: typeof AuthenticatedKnowledgeWechatRoute
  AuthenticatedManagementAiModelsRoute: typeof AuthenticatedManagementAiModelsRoute
  AuthenticatedManagementUsersRoute: typeof AuthenticatedManagementUsersRoute
  AuthenticatedAiChatsIndexRoute: typeof AuthenticatedAiChatsIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedManagementIndexRoute: typeof AuthenticatedManagementIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedDocumentsSettingsCategoriesRoute: typeof AuthenticatedDocumentsSettingsCategoriesRoute
  AuthenticatedDocumentsSettingsKnowledgeQualityAssessmentRoute: typeof AuthenticatedDocumentsSettingsKnowledgeQualityAssessmentRoute
  AuthenticatedManagementOrganizationChartRoute: typeof AuthenticatedManagementOrganizationChartRoute
  AuthenticatedManagementOrganizationHierarchyRoute: typeof AuthenticatedManagementOrganizationHierarchyRoute
  AuthenticatedManagementOrganizationUsersRoute: typeof AuthenticatedManagementOrganizationUsersRoute
  AuthenticatedManagementSecurityAccessRoute: typeof AuthenticatedManagementSecurityAccessRoute
  AuthenticatedManagementSecurityAuditRoute: typeof AuthenticatedManagementSecurityAuditRoute
  AuthenticatedManagementSecurityPasswordPoliciesRoute: typeof AuthenticatedManagementSecurityPasswordPoliciesRoute
  AuthenticatedManagementSecurityRolesRoute: typeof AuthenticatedManagementSecurityRolesRoute
  AuthenticatedManagementSystemAiModelsRoute: typeof AuthenticatedManagementSystemAiModelsRoute
  AuthenticatedManagementSystemConfigRoute: typeof AuthenticatedManagementSystemConfigRoute
  AuthenticatedManagementSystemIntegrationsRoute: typeof AuthenticatedManagementSystemIntegrationsRoute
  AuthenticatedManagementSystemTenantsRoute: typeof AuthenticatedManagementSystemTenantsRoute
  AuthenticatedManagementSystemUsersRoute: typeof AuthenticatedManagementSystemUsersRoute
  AuthenticatedAuthOauthCallbackProviderRoute: typeof AuthenticatedAuthOauthCallbackProviderRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDocumentsFavoritesRoute: AuthenticatedDocumentsFavoritesRoute,
  AuthenticatedDocumentsRecentRoute: AuthenticatedDocumentsRecentRoute,
  AuthenticatedDocumentsSharedRoute: AuthenticatedDocumentsSharedRoute,
  AuthenticatedDocumentsStorageRoute: AuthenticatedDocumentsStorageRoute,
  AuthenticatedDocumentsTrashRoute: AuthenticatedDocumentsTrashRoute,
  AuthenticatedKnowledgeDepartmentsRoute:
    AuthenticatedKnowledgeDepartmentsRoute,
  AuthenticatedKnowledgeGraphRoute: AuthenticatedKnowledgeGraphRoute,
  AuthenticatedKnowledgeOrganizationsRoute:
    AuthenticatedKnowledgeOrganizationsRoute,
  AuthenticatedKnowledgeWebBlogsRoute: AuthenticatedKnowledgeWebBlogsRoute,
  AuthenticatedKnowledgeWechatRoute: AuthenticatedKnowledgeWechatRoute,
  AuthenticatedManagementAiModelsRoute: AuthenticatedManagementAiModelsRoute,
  AuthenticatedManagementUsersRoute: AuthenticatedManagementUsersRoute,
  AuthenticatedAiChatsIndexRoute: AuthenticatedAiChatsIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedManagementIndexRoute: AuthenticatedManagementIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedDocumentsSettingsCategoriesRoute:
    AuthenticatedDocumentsSettingsCategoriesRoute,
  AuthenticatedDocumentsSettingsKnowledgeQualityAssessmentRoute:
    AuthenticatedDocumentsSettingsKnowledgeQualityAssessmentRoute,
  AuthenticatedManagementOrganizationChartRoute:
    AuthenticatedManagementOrganizationChartRoute,
  AuthenticatedManagementOrganizationHierarchyRoute:
    AuthenticatedManagementOrganizationHierarchyRoute,
  AuthenticatedManagementOrganizationUsersRoute:
    AuthenticatedManagementOrganizationUsersRoute,
  AuthenticatedManagementSecurityAccessRoute:
    AuthenticatedManagementSecurityAccessRoute,
  AuthenticatedManagementSecurityAuditRoute:
    AuthenticatedManagementSecurityAuditRoute,
  AuthenticatedManagementSecurityPasswordPoliciesRoute:
    AuthenticatedManagementSecurityPasswordPoliciesRoute,
  AuthenticatedManagementSecurityRolesRoute:
    AuthenticatedManagementSecurityRolesRoute,
  AuthenticatedManagementSystemAiModelsRoute:
    AuthenticatedManagementSystemAiModelsRoute,
  AuthenticatedManagementSystemConfigRoute:
    AuthenticatedManagementSystemConfigRoute,
  AuthenticatedManagementSystemIntegrationsRoute:
    AuthenticatedManagementSystemIntegrationsRoute,
  AuthenticatedManagementSystemTenantsRoute:
    AuthenticatedManagementSystemTenantsRoute,
  AuthenticatedManagementSystemUsersRoute:
    AuthenticatedManagementSystemUsersRoute,
  AuthenticatedAuthOauthCallbackProviderRoute:
    AuthenticatedAuthOauthCallbackProviderRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
